---
title: "EpscorMetabCleaning"
author: "Jacob Adams"
date: "1/26/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggpubr)
library(anytime)
library(googlesheets4)
library(ggpmisc)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(scales)
library(zoo)
library(xts)
library(forecast)
library(googledrive)
library(streamMetabolizer)
library(readr)
library(here)
library(rstan)
library(imputeTS)
library(itsmr)
library(purrr)
library(naniar)
library(data.table)
library(grid)
library(ggtext)
```



DO and Temp data:

```{r}
#from internal log script

CrawMiniDot <- read.csv(here("outputs", "craw.clean.miniDOT.csv")) 
CrawMiniDot <- CrawMiniDot %>% rename(DO.obs.upstream = DO.obs.CUS, DO.obs.downstream = DO.obs.CDS, temp.water.upstream = temp.water.CUS, temp.water.downstream = temp.water.CDS)

MastMiniDot <- read.csv(here("outputs", "mast.clean.miniDOT.csv"))
MastMiniDot <- MastMiniDot %>% rename(DO.obs.upstream = DO.obs.MUS, DO.obs.downstream = DO.obs.MDS, temp.water.upstream = temp.water.MUS, temp.water.downstream = temp.water.MDS)
MastMiniDot$Site <- "MAST"

ShovMiniDot <- read.csv(here("outputs", "shov.clean.miniDOT.csv"))
ShovMiniDot <- ShovMiniDot %>% rename(DO.obs.upstream = DO.obs.SUS, DO.obs.downstream = DO.obs.SDS, temp.water.upstream = temp.water.SUS, temp.water.downstream = temp.water.SDS)


EpscorMiniDot <- rbind(CrawMiniDot,MastMiniDot,ShovMiniDot)




```



```{r}



```