---
title: "FinalFrench_Run"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#2019

```{r data}
setwd(here())
FRCH.comb.in <- read.csv(here("outputs", "frch.comb.csv"))

#Set year of 2019
FRCH.comb.in <- FRCH.comb.in %>% filter(datetimeAK >= "2019-04-29 14:30:00" & datetimeAK < "2019-10-09 23:45:00")


anyNA(FRCH.comb.in, recursive = TRUE)
lapply(FRCH.comb.in, summary)

FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-06-27 14:15:00", NA, .)))

FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-07-19 10:15:00", NA, .)))

FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-07-26 13:45:00", NA, .)))

FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-07-26 14:00:00", NA, .)))


FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-06-13 14:00:00", NA, .)))


FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-06-13 13:45:00", NA, .)))



FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-06-13 14:00:00", NA, .)))


FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-07-12 09:45:00", NA, .)))


FRCH.comb.in <- FRCH.comb.in %>%
  mutate(across(c(temp.water, ODO.Psat, ODO.Ploc, DO.obs, DO.sat.EXO, DO.sat),
                ~ifelse(datetimeAK == "2019-09-26 13:00:00", NA, .)))

#NA FILL OUT OF WATER and Other small gaps
FRCH.comb.in$temp.water <- na_kalman(FRCH.comb.in$temp.water)
FRCH.comb.in$ODO.Psat <- na_kalman(FRCH.comb.in$ODO.Psat)
FRCH.comb.in$DO.obs <- na_kalman(FRCH.comb.in$DO.obs, type = "level")
FRCH.comb.in$DO.sat <- na_kalman(FRCH.comb.in$DO.sat, type = "level")
FRCH.comb.in$DO.sat.EXO <- na_kalman(FRCH.comb.in$DO.sat.EXO, type = "level")
FRCH.comb.in$depth <- na_kalman(FRCH.comb.in$depth, type = "level")
FRCH.comb.in$discharge <- na_kalman(FRCH.comb.in$discharge, type = "level")



#Set time of run
# FRCH.comb <- FRCH.comb.in %>% filter(solar.time >= "2019-04-28 04:13:57" & solar.time < "2019-06-16 04:13:57")



anyNA(FRCH.comb.in, recursive = TRUE)
lapply(FRCH.comb.in, summary)

FRCH.comb<- FRCH.comb.in

FRCH.comb$datetimeAK <- force_tz(as.POSIXct(FRCH.comb$datetimeAK), "America/Anchorage")

FRCH.comb$solar.time <- calc_solar_time(as.POSIXct(FRCH.comb$datetimeAK), longitude = -146.916364)


#DO sat is DO sat EXO, duplicate cols
data.frch.mm.2019 <- FRCH.comb %>%
  select(datetimeAK, solar.time, depth, DO.obs, DO.sat, temp.water, light, discharge)

anyNA(data.frch.mm.2019, recursive = TRUE)
lapply(data.frch.mm.2019, summary)



#Data after AUG 1 is bad: 
data.frch.mm.2019 <- data.frch.mm.2019 %>% filter(solar.time < "2019-08-01  04:13:57")



```


#2020
``` {r}
setwd(here())
FRCH.comb.in <- read.csv(here("outputs", "frch.comb.csv"))

FRCH.comb.in2020.1 <- FRCH.comb.in %>% filter(datetimeAK >= "2020-06-11 14:00:00" & datetimeAK < "2020-06-13 18:00:00")


FRCH.comb.in2020.2 <- FRCH.comb.in %>% filter(datetimeAK >= "2020-08-25 11:15:00" & datetimeAK < "2020-10-13 23:45:00")


FRCH.comb.in2020 <- rbind(FRCH.comb.in2020.1,FRCH.comb.in2020.2)

anyNA(FRCH.comb.in2020, recursive = TRUE)
lapply(FRCH.comb.in2020, summary)

#NA FILL OUT OF WATER and Other small gaps
FRCH.comb.in2020$temp.water <- na_kalman(FRCH.comb.in2020$temp.water, type = "level")
FRCH.comb.in2020$ODO.Psat <- na_kalman(FRCH.comb.in2020$ODO.Psat)
FRCH.comb.in2020$DO.obs <- na_kalman(FRCH.comb.in2020$DO.obs, type = "level")
FRCH.comb.in2020$DO.sat <- na_kalman(FRCH.comb.in2020$DO.sat, type = "level")
FRCH.comb.in2020$DO.sat.EXO <- na_kalman(FRCH.comb.in2020$DO.sat.EXO, type = "level")
FRCH.comb.in2020$depth <- na_kalman(FRCH.comb.in2020$depth, type = "level")
FRCH.comb.in2020$discharge <- na_kalman(FRCH.comb.in2020$discharge, type = "level")


anyNA(FRCH.comb.in2020, recursive = TRUE)
lapply(FRCH.comb.in2020, summary)

FRCH.comb.in2020$datetimeAK <- force_tz(as.POSIXct(FRCH.comb.in2020$datetimeAK), "America/Anchorage")

FRCH.comb.in2020$solar.time <- calc_solar_time(as.POSIXct(FRCH.comb.in2020$datetimeAK), longitude = -146.916364)


#DO sat is DO sat EXO, duplicate cols
data.frch.mm.2020 <- FRCH.comb.in2020 %>%
  select(datetimeAK, solar.time, depth, DO.obs, DO.sat, temp.water, light, discharge)

anyNA(data.frch.mm.2020, recursive = TRUE)
lapply(data.frch.mm.2020, summary)



```



#2021
``` {r}
setwd(here())
FRCH.comb.in <- read.csv(here("outputs", "frch.comb.csv"))

#Q data bad until 6/30, No EXO data after 7/12
FRCH.comb.in2021.1 <- FRCH.comb.in %>% filter(datetimeAK >= "2021-06-30 03:00:00")

FRCH.comb.in2021.1 <- FRCH.comb.in2021.1 %>% filter(datetimeAK < "2021-07-12 10:00:00")

#EXO back on 7/26, until end of season.
FRCH.comb.in2021.2 <- FRCH.comb.in %>% filter(datetimeAK >= "2021-07-26 12:00:00")

FRCH.comb.in2021.2 <- FRCH.comb.in2021.2 %>% filter(datetimeAK < "2021-09-26 23:45:00")


FRCH.comb.in2021 <- rbind(FRCH.comb.in2021.1,FRCH.comb.in2021.2)

anyNA(FRCH.comb.in2021, recursive = TRUE)
lapply(FRCH.comb.in2021, summary)


#NA FILL OUT OF WATER and Other small gaps
FRCH.comb.in2021$temp.water <- na_kalman(FRCH.comb.in2021$temp.water, type = "level")
FRCH.comb.in2021$ODO.Psat <- na_kalman(FRCH.comb.in2021$ODO.Psat)
FRCH.comb.in2021$DO.obs <- na_kalman(FRCH.comb.in2021$DO.obs, type = "level")
FRCH.comb.in2021$DO.sat <- na_kalman(FRCH.comb.in2021$DO.sat, type = "level")
FRCH.comb.in2021$DO.sat.EXO <- na_kalman(FRCH.comb.in2021$DO.sat.EXO, type = "level")
FRCH.comb.in2021$depth <- na_kalman(FRCH.comb.in2021$depth, type = "level")
FRCH.comb.in2021$discharge <- na_kalman(FRCH.comb.in2021$discharge, type = "level")


anyNA(FRCH.comb.in2021, recursive = TRUE)
lapply(FRCH.comb.in2021, summary)


FRCH.comb.in2021$datetimeAK <- force_tz(as.POSIXct(FRCH.comb.in2021$datetimeAK), "America/Anchorage")

FRCH.comb.in2021$solar.time <- calc_solar_time(as.POSIXct(FRCH.comb.in2021$datetimeAK), longitude = -146.916364)


#DO sat is DO sat EXO, duplicate cols
data.frch.mm.2021 <- FRCH.comb.in2021 %>%
  select(datetimeAK, solar.time, depth, DO.obs, DO.sat, temp.water, light, discharge)

anyNA(data.frch.mm.2021, recursive = TRUE)
lapply(data.frch.mm.2021, summary)



```

Met tower Light, then Combine years and save

``` {r}

anyNA(data.frch.mm.all, recursive = TRUE)
lapply(data.frch.mm.all, summary)


CRREL <- read.csv(here("MetTowerData.csv"), skip = 5)

CRREL$datetimeAK <- as.POSIXct(CRREL$Time, tz = "America/Anchorage")

CRREL <- CRREL %>% rename(ParWm2 = CPCRW.CRREL.Main.Met.Station..PAR_Den_AVG.W.m2.)


#2019
CRREL_FRCH.2019 <- left_join(data.frch.mm.2019,CRREL, by = "datetimeAK")

CRREL_FRCH.2019$ParWm2 <- na_kalman(CRREL_FRCH.2019$ParWm2)



#### POKE 2019 ####
PAR.2019.url <- "https://drive.google.com/drive/u/1/folders/11kWuwCF6pTXYolwYnxcsX6OcYyQeF35z"
PAR_19.prt1 <- drive_get(as_id(PAR.2019.url))
poke_par_glist <- drive_ls(PAR_19.prt1, pattern = "191017_11619_POKE.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2019.Data <- read.csv("191017_11619_POKE.CSV",
                               skip = 8, header = FALSE)
poke.par.2019.Data <- poke.par.2019.Data %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)

#Fix Date Time
poke.par.2019.Data$DateTime <- paste(poke.par.2019.Data$Date, poke.par.2019.Data$Time, sep="")

poke.par.2019.Data$DateTime <-  dmy_hms(poke.par.2019.Data$DateTime)
poke.par.2019.Data$DateTime <- force_tz(poke.par.2019.Data$DateTime, "America/Anchorage")

#Calibrate logger 11619 to LICOR
poke.par.2019.Data$CalibratedValue <- poke.par.2019.Data$CalibratedValue * 0.035


max.par.poke.2019 <- max(poke.par.2019.Data$CalibratedValue)

max.par.crrel.2019 <- max(CRREL_FRCH.2019$ParWm2)

multiplyFactor.2019 <- max.par.poke.2019/max.par.crrel.2019


CRREL_FRCH.2019$ParMetCor <- CRREL_FRCH.2019$ParWm2 *multiplyFactor.2019








#### POKE 2020 ####
PAR.2020.url <- "https://drive.google.com/drive/u/1/folders/1udve7khOM2EX0l8BZQK3yehb2HUbwFtR"
PAR_2020.prt1 <- drive_get(as_id(PAR.2020.url))
poke_par_glist <- drive_ls(PAR_2020.prt1, pattern = "11619_002_002_POKE_EndOfSeason.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2020.Data <- read.csv("11619_002_002_POKE_EndOfSeason.CSV",
                               skip = 9, header = FALSE)
poke.par.2020.Data <- poke.par.2020.Data %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)
#Fix Date Time
poke.par.2020.Data$DateTime <- paste(poke.par.2020.Data$Date, poke.par.2020.Data$Time, sep="")
poke.par.2020.Data$DateTime <-  dmy_hms(poke.par.2020.Data$DateTime)
poke.par.2020.Data$DateTime <- force_tz(poke.par.2020.Data$DateTime, "America/Anchorage")

#Calibrate logger 11619 to LICOR
poke.par.2020.Data$CalibratedValue <- poke.par.2020.Data$CalibratedValue * 0.035

#2020
CRREL_FRCH.2020 <- left_join(data.frch.mm.2020,CRREL, by = "datetimeAK")

CRREL_FRCH.2020$ParWm2 <- na_kalman(CRREL_FRCH.2020$ParWm2)


max.par.poke.2020 <- max(poke.par.2020.Data$CalibratedValue)

max.par.crrel.2020 <- max(CRREL_FRCH.2020$ParWm2)

multiplyFactor.2020 <- max.par.poke.2020/max.par.crrel.2020


CRREL_FRCH.2020$ParMetCor <- CRREL_FRCH.2020$ParWm2 *multiplyFactor.2020




#2021
###### 2021 #####
PAR.2021.url <- "https://drive.google.com/drive/u/1/folders/1EPjHLDmfbCo5n12AKj7QpN2vXRCPQtg5"
PAR_2021.prt1 <- drive_get(as_id(PAR.2021.url))
par2021_glist <- drive_ls(PAR_2021.prt1, pattern = "all.dates.par.2021.csv")
walk(par2021_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
par2021.Data <- read.csv("all.dates.par.2021.csv",
                         skip = 0, header = TRUE)
# Sort into sites
poke.par2021.Data <- par2021.Data %>% filter(site == "poke")

poke.par2021.Data <- poke.par2021.Data %>%
  dplyr::rename(RawValue = V5)

poke.par2021.Data$DateTime <- as.POSIXct(poke.par2021.Data$DateTime)

#Calibrate loggers to LICOR
poke.par2021.Data$Calibrated.Value <- poke.par2021.Data$Calibrated.Value * 0.035



#2021
CRREL_FRCH.2021 <- left_join(data.frch.mm.2021,CRREL, by = "datetimeAK")

CRREL_FRCH.2021$ParWm2 <- na_kalman(CRREL_FRCH.2021$ParWm2)


max.par.poke.2021 <- max(poke.par2021.Data$Calibrated.Value)

max.par.crrel.2021 <- max(CRREL_FRCH.2021$ParWm2)

multiplyFactor.2021 <- max.par.poke.2021/max.par.crrel.2021


CRREL_FRCH.2021$ParMetCor <- CRREL_FRCH.2021$ParWm2 *multiplyFactor.2021




#save for analysis
data.frch.mm.all <- rbind(CRREL_FRCH.2019, CRREL_FRCH.2020, CRREL_FRCH.2021)

data.frch.mm.all$light <- data.frch.mm.all$ParMetCor

data.frch.mm.all <- data.frch.mm.all %>% 
  select(solar.time, depth, DO.obs, DO.sat, temp.water, light, discharge)


anyNA(data.frch.mm.all, recursive = TRUE)
lapply(data.frch.mm.all, summary)

write.csv(data.frch.mm.all, here("outputs", "french.comb.readyforMetab.csv"))


```





``` {r}
 rm(list = ls())


```


#Metab 2019


```{r}


# 2. Configuring the model


bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name

bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_name_AppEtAL


bayes_specs <- specs(bayes_name, 
                     burnin_steps=9000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

```


``` {r}
date.list <- c(unique(as.Date(data.frch.mm.all$solar.time)))

```


```{r fig.width=8, fig.height=10}

data.frch.mm.all <- read.csv(here("outputs", "french.comb.readyforMetab.csv"))


#split 2019
data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time > "2019-04-29 12:43:57" & solar.time <= "2019-06-20 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2019-06-19 12:43:57" & solar.time <= "2019-08-02 04:13:57")
# 
# #Try all of 2020
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2020-04-01 12:43:57" & solar.time <= "2020-11-20 04:13:57")
# 
# 
# #split 2021
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-06-01 12:43:57" & solar.time <= "2021-08-25 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-08-22 12:43:57" & solar.time <= "2021-11-22 04:13:57")
data.frch.mm.all$solar.time <- as.POSIXct(data.frch.mm.all$solar.time, tz = "UTC")

data.frch.mm.all <- data.frch.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.frch <- metab(bayes_specs, data=data.frch.mm.all)
endTime <- as.POSIXct(Sys.time())

difftime(endTime, startTime)
save(mm.test.frch, file = here("Outputs", "frch.2019.1.RData"))


fit.frch <- get_fit(mm.test.frch)
fit.daily <- fit.frch$daily
write.csv(fit.daily, here("outputs", "frch.2019.1.full.csv"))

```

``` {r fig.width=15, fig.height=8}
#Plots
gpp <- ggplot(data=fit.frch$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=fit.frch$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

rhat <- ggplot(data=fit.frch$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(mm.test.frch)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))


grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())


```



```{r fig.width=8, fig.height=10}

# 2. Configuring the model


bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name

bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_name_AppEtAL


bayes_specs <- specs(bayes_name, 
                     burnin_steps=9000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

data.frch.mm.all <- read.csv(here("outputs", "french.comb.readyforMetab.csv"))


#split 2019
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time > "2019-04-29 12:43:57" & solar.time <= "2019-06-20 04:13:57")
# 
data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2019-06-19 12:43:57" & solar.time <= "2019-08-02 04:13:57")
# 
# #Try all of 2020
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2020-04-01 12:43:57" & solar.time <= "2020-11-20 04:13:57")
# 
# 
# #split 2021
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-06-01 12:43:57" & solar.time <= "2021-08-25 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-08-22 12:43:57" & solar.time <= "2021-11-22 04:13:57")
data.frch.mm.all$solar.time <- as.POSIXct(data.frch.mm.all$solar.time, tz = "UTC")

data.frch.mm.all <- data.frch.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.frch <- metab(bayes_specs, data=data.frch.mm.all)
endTime <- as.POSIXct(Sys.time())

difftime(endTime, startTime)
save(mm.test.frch, file = here("Outputs", "frch.2019.2.RData"))
load(here("Outputs", "frch.2019.2.RData"))

fit.frch <- get_fit(mm.test.frch)
fit.daily <- fit.frch$daily
write.csv(fit.daily, here("outputs", "frch.2019.2.full.csv"))

```

``` {r fig.width=15, fig.height=8}
#Plots
gpp <- ggplot(data=fit.frch$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=fit.frch$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

rhat <- ggplot(data=fit.frch$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(mm.test.frch)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))


grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())


```

```{r fig.width=8, fig.height=10}

# 2. Configuring the model


bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name

bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_name_AppEtAL


bayes_specs <- specs(bayes_name, 
                     burnin_steps=9000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

data.frch.mm.all <- read.csv(here("outputs", "french.comb.readyforMetab.csv"))


#split 2019
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time > "2019-04-29 12:43:57" & solar.time <= "2019-06-20 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2019-06-19 12:43:57" & solar.time <= "2019-08-02 04:13:57")
# 
# #Try all of 2020
data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2020-04-01 12:43:57" & solar.time <= "2020-11-20 04:13:57")
# 
# 
# #split 2021
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-06-01 12:43:57" & solar.time <= "2021-08-25 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-08-22 12:43:57" & solar.time <= "2021-11-22 04:13:57")
data.frch.mm.all$solar.time <- as.POSIXct(data.frch.mm.all$solar.time, tz = "UTC")

data.frch.mm.all <- data.frch.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.frch <- metab(bayes_specs, data=data.frch.mm.all)
endTime <- as.POSIXct(Sys.time())

difftime(endTime, startTime)
save(mm.test.frch, file = here("Outputs", "frch.2020.1.RData"))


fit.frch <- get_fit(mm.test.frch)
fit.daily <- fit.frch$daily
write.csv(fit.daily, here("outputs", "frch.2020.1.full.csv"))

```

``` {r fig.width=15, fig.height=8}
#Plots
gpp <- ggplot(data=fit.frch$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=fit.frch$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

rhat <- ggplot(data=fit.frch$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(mm.test.frch)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))


grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())


```

```{r fig.width=8, fig.height=10}

# 2. Configuring the model


bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name

bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_name_AppEtAL


bayes_specs <- specs(bayes_name, 
                     burnin_steps=9000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

data.frch.mm.all <- read.csv(here("outputs", "french.comb.readyforMetab.csv"))


#split 2019
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time > "2019-04-29 12:43:57" & solar.time <= "2019-06-20 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2019-06-19 12:43:57" & solar.time <= "2019-08-02 04:13:57")
# 
# #Try all of 2020
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2020-04-01 12:43:57" & solar.time <= "2020-11-20 04:13:57")
# 
# 
# #split 2021
data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-06-01 12:43:57" & solar.time <= "2021-08-25 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-08-22 12:43:57" & solar.time <= "2021-11-22 04:13:57")
data.frch.mm.all$solar.time <- as.POSIXct(data.frch.mm.all$solar.time, tz = "UTC")

data.frch.mm.all <- data.frch.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.frch <- metab(bayes_specs, data=data.frch.mm.all)
endTime <- as.POSIXct(Sys.time())

difftime(endTime, startTime)
save(mm.test.frch, file = here("Outputs", "frch.2022.1.RData"))


fit.frch <- get_fit(mm.test.frch)
fit.daily <- fit.frch$daily
write.csv(fit.daily, here("outputs", "frch.2022.1.full.csv"))

```

``` {r fig.width=15, fig.height=8}
#Plots
gpp <- ggplot(data=fit.frch$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=fit.frch$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

rhat <- ggplot(data=fit.frch$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(mm.test.frch)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))


grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())


```

```{r fig.width=8, fig.height=10}

# 2. Configuring the model


bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name

bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_name_AppEtAL


bayes_specs <- specs(bayes_name, 
                     burnin_steps=9000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

data.frch.mm.all <- read.csv(here("outputs", "french.comb.readyforMetab.csv"))


#split 2019
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time > "2019-04-29 12:43:57" & solar.time <= "2019-06-20 04:13:57")
# 
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2019-06-19 12:43:57" & solar.time <= "2019-08-02 04:13:57")
# 
# #Try all of 2020
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2020-04-01 12:43:57" & solar.time <= "2020-11-20 04:13:57")
# 
# 
# #split 2021
# data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-06-01 12:43:57" & solar.time <= "2021-08-25 04:13:57")
# 
data.frch.mm.all <- data.frch.mm.all %>% filter(solar.time >= "2021-08-22 12:43:57" & solar.time <= "2021-11-22 04:13:57")
data.frch.mm.all$solar.time <- as.POSIXct(data.frch.mm.all$solar.time, tz = "UTC")

data.frch.mm.all <- data.frch.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.frch <- metab(bayes_specs, data=data.frch.mm.all)
endTime <- as.POSIXct(Sys.time())

difftime(endTime, startTime)
save(mm.test.frch, file = here("Outputs", "frch.2021.2.RData"))


fit.frch <- get_fit(mm.test.frch)
fit.daily <- fit.frch$daily
write.csv(fit.daily, here("outputs", "frch.2021.2.full.csv"))

```

``` {r fig.width=15, fig.height=8}
#Plots
gpp <- ggplot(data=fit.frch$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=fit.frch$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

rhat <- ggplot(data=fit.frch$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(mm.test.frch)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))


grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())


```

Final Plots
``` {r}

frch2019.1 <- read.csv(here("outputs","frch.2019.1.full.csv")) %>% filter(date <= "2019-06-19")
frch2019.2 <- read.csv(here("outputs","frch.2019.2.full.csv"))%>% filter(date >= "2019-06-20")

frch2020 <- read.csv(here("outputs","frch.2020.1.full.csv"))

frch2021.1 <- read.csv(here("outputs","frch.2022.1.full.csv")) %>% filter(date<= "2021-08-24")
frch2021.2 <- read.csv(here("outputs","frch.2022.2.full.csv")) %>% filter(date>= "2021-08-25")

frch.all <- rbind(frch2019.1, frch2019.2, frch2020, frch2021.1, frch2021.2)

frch.all$date <- as.POSIXct(frch.all$date)



# 
# same2019 <- inner_join(frch2019.1, frch2019.2, by = "date")
# 
# same2021 <- inner_join(frch2021.1, frch2021.2, by = "date")
# 
# str(same2021)
# 
# same2021$date <- as.Date(same2021$date)
# same2021 %>% filter(date>= "2021-08-23" & date <= "2021-08-24")%>% ggplot(aes(x= date)) + geom_point(aes(y = GPP_mean.x, color = "First Chunk"))+ geom_errorbar(aes(ymin=GPP_mean.x-GPP_sd.x, ymax=GPP_mean.x+GPP_sd.x)) + geom_point(aes(y = GPP_mean.y, color="Second Chunk")) + geom_errorbar(aes(ymin=GPP_mean.y-GPP_sd.y, ymax=GPP_mean.y+GPP_sd.y)) + ggtitle("French 2021 Run overlaps")
# 
# 
# same2021$date <- as.Date(same2021$date)
# gppoverlap <- same2021 %>% filter(date>= "2021-08-23" & date <= "2021-08-24")%>% ggplot(aes(x= date)) + geom_point(aes(y = ER_mean.x, color = "First Chunk"))+ geom_errorbar(aes(ymin=ER_mean.x-ER_sd.x, ymax=ER_mean.x+ER_sd.x)) + geom_point(aes(y = ER_mean.y, color="Second Chunk")) + geom_errorbar(aes(ymin=ER_mean.y-ER_sd.y, ymax=ER_mean.y+ER_sd.y)) + ggtitle("French 2021 Run overlaps")
# 
# same2021$date <- as.Date(same2021$date)
# ERoverlap <- same2021 %>% filter(date>= "2021-08-23" & date <= "2021-08-24")%>% ggplot(aes(x= date)) + geom_point(aes(y = ER_mean.x, color = "First Chunk"))+ geom_errorbar(aes(ymin=ER_mean.x-ER_sd.x, ymax=ER_mean.x+ER_sd.x)) + geom_point(aes(y = ER_mean.y, color="Second Chunk")) + geom_errorbar(aes(ymin=ER_mean.y-ER_sd.y, ymax=ER_mean.y+ER_sd.y)) + ggtitle("French 2021 Run overlaps")
# 
# same2021$date <- as.Date(same2021$date)
# k600overlap <- same2021 %>% filter(date>= "2021-08-23" & date <= "2021-08-24")%>% ggplot(aes(x= date)) + geom_point(aes(y = K600_daily_mean.x, color = "First Chunk"))+ geom_errorbar(aes(ymin=K600_daily_mean.x-K600_daily_sd.x, ymax=K600_daily_mean.x+K600_daily_sd.x)) + geom_point(aes(y = K600_daily_mean.y, color="Second Chunk")) + geom_errorbar(aes(ymin=K600_daily_mean.y-K600_daily_sd.y, ymax=K600_daily_mean.y+K600_daily_sd.y)) + ggtitle("French 2021 Run overaps")
# 
# 
# ggarrange(gppoverlap, ERoverlap, k600overlap)


#Plots
gpp <- ggplot(data=frch.all, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

er <- ggplot(data = frch.all, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")

k600 <- ggplot(data=frch.all, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) +ggtitle("French Metabolism 2019- 2021")

rhat <- ggplot(data=frch.all, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


ggplot(data=frch.all, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
ggplot(data=frch.all, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 

ggplot(data=frch.all, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
dev.set(dev.next())

mcmc <- get_mcmc(frch.all)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=3)
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=3)
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=3)

library(grid)

grid.newpage()
grid.draw(rbind(ggplotGrob(k600mcmc), ggplotGrob(gppmcmc), ggplotGrob(ermcmc)))


#DO r2
frch.DO.pred <- predict_DO(mm.test.frch)
frch.DO.pred <- na.omit(frch.DO.pred)
lm(DO.obs~ DO.mod, data = frch.DO.pred)
frch.DO.pred$SM.date <- as.Date(frch.DO.pred$solar.time - 4*60*60)
frch.DO.pred$SM.date <- as.factor(frch.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- frch.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
frch.DO.pred <- full_join(frch.DO.pred, test.run)
rsq <-  summary(lm(frch.DO.pred$DO.mod~frch.DO.pred$DO.obs))$r.squared
library(ggplot2)
p1 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(frch.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.frch.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))



grid.newpage()
grid.draw(rbind(ggplotGrob(rhat),ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))


rm(list = ls())

frch.all$doy <- sapply(frch.all$date, function(x) julian(x, origin = as.POSIXct(paste0(format(x, "%Y"),'-01-01'), tz = 'America/Anchorage')))

#Figure out how to facet 


```
