---
title: "PlotsForTKH"
author: "Jacob Adams"
date: "2/6/2023"
output: html_document
---

```{r}
library(ggpubr)
library(anytime)
library(googlesheets4)
library(ggpmisc)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(scales)
library(zoo)
library(xts)
library(forecast)
library(googledrive)
library(streamMetabolizer)
library(readr)
library(here)
library(rstan)
library(imputeTS)
library(itsmr)
library(purrr)
library(naniar)
library(data.table)
library(grid)
library(ggtext)
library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)

```


```{r}

frch.metab <- read.csv(here("outputs", "french2019-Run_2023-Full.rerun.02.04.csv"))
frch.metab$date <- as.POSIXct(frch.metab$date)


# grob <- grobTree(textGrob("2019", x="2019-09-01", y=4, hjust=0,
#   gp=gpar(col="black", fontsize=20, fontface="italic")))
# Plo





gpp2019 <- ggplot(data=frch.metab, aes(x=(date), y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 15)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+ annotate("text", x= as.POSIXct("2019-09-11"), y=max(frch.metab$GPP_mean),label="2019")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ annotation_custom(grobTree(textGrob("2019", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))









frch.comb <- read.csv(here("outputs", "frch.comb.csv"))
frch.comb$solar.time <- as.POSIXct(frch.comb$solar.time, tz = "UTC")

frch.comb$discharge  <- frch.comb$discharge 


q.fig2019 <-  frch.comb %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 5000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

#L.fig <- frch.comb  %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(frch.comb$light))


panGPP <- ggplotGrob(gpp2019)
 
panQ <- ggplotGrob(q.fig2019)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2019 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "frch2019.gpp.q.pdf", fig2019, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
frch.metab <- read.csv(here("outputs", "french2020-Run_2023-Full.rerun.02.04.csv"))
frch.metab$date <- as.POSIXct(frch.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2020 <- ggplot(data=frch.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 15) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2020", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


frch.comb <- read.csv(here("outputs", "frch.comb.csv"))
frch.comb$solar.time <- as.POSIXct(frch.comb$solar.time, tz = "UTC")

frch.comb$discharge  <- frch.comb$discharge 



q.fig2020 <-  frch.comb %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 5000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )


#L.fig <- frch.comb  %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(frch.comb$light))


panGPP <- ggplotGrob(gpp2020)
 
panQ <- ggplotGrob(q.fig2020)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2020 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "frch2020.gpp.q.pdf", fig2020, width = 12,  height = 6, units = "in", limitsize = FALSE)


```


```{r}
frch.metab <- read.csv(here("outputs", "french2021-Run_2023-Full.rerun.02.04.csv"))
frch.metab$date <- as.POSIXct(frch.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2021 <- ggplot(data=frch.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 15) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))+ annotation_custom(grobTree(textGrob("2021", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))



frch.comb <- read.csv(here("outputs", "frch.comb.csv"))
frch.comb$solar.time <- as.POSIXct(frch.comb$solar.time, tz = "UTC")

frch.comb$discharge  <- frch.comb$discharge 


q.fig2021 <-  frch.comb %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 5000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))


#L.fig <- frch.comb  %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(frch.comb$light))


panGPP <- ggplotGrob(gpp2021)
 
panQ <- ggplotGrob(q.fig2021)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2021 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "frch2021.gpp.q.pdf", fig2021, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
frch.metab <- read.csv(here("outputs", "french2022-Run_2023-Full.rerun.02.04.csv"))
frch.metab$date <- as.POSIXct(frch.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2022 <- ggplot(data=frch.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 15) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2022", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


frch.comb <- read.csv(here("outputs", "frch.comb.csv"))
frch.comb$solar.time <- as.POSIXct(frch.comb$solar.time, tz = "UTC")

frch.comb$discharge  <- frch.comb$discharge 


q.fig2022 <-  frch.comb %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 5000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00"))) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )



#L.fig <- frch.comb  %>% filter(datetimeAK >= min(frch.metab$date)) %>% filter(datetimeAK <= max(frch.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(frch.comb$light))


panGPP <- ggplotGrob(gpp2022)
 
panQ <- ggplotGrob(q.fig2022)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "frch2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}

library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)
# If that doesnt do it, add grid

#devtools::install_github("thomasp85/patchwork")
library(patchwork)


plottest <- gpp2019+ggtitle("French Creek")+theme(plot.title = element_text(size = 30, hjust = 0)) + gpp2020 + q.fig2019+q.fig2020 + gpp2021+gpp2022+q.fig2021+q.fig2022 + plot_layout(ncol = 2, widths = c(2, 2))

ggsave(path = here("plots"), file = "frch.gpp.q.all.pdf", plottest, width = 11*1.3,  height = 8.5*1.3, units = "in", limitsize = FALSE)



```




##### Q and and also tmep and DO

```{r}

moos.metab <- read.csv(here("outputs", "moose2019-Run_2023-Full.rerun.02.04.csv"))
moos.metab$date <- as.POSIXct(moos.metab$date)


# grob <- grobTree(textGrob("2019", x="2019-09-01", y=4, hjust=0,
#   gp=gpar(col="black", fontsize=20, fontface="italic")))
# Plo





gpp2019 <- ggplot(data=moos.metab, aes(x=(date), y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 7)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+ annotate("text", x= as.POSIXct("2019-09-11"), y=max(moos.metab$GPP_mean),label="2019")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ annotation_custom(grobTree(textGrob("2019", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))









moos.comb <- read.csv(here("outputs", "clean.moos.2019.full.csv"))
moos.comb$solar.time <- as.POSIXct(moos.comb$solar.time, tz = "UTC")

moos.comb$discharge  <- moos.comb$discharge 

DO.fig2019 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=DO.obs), color = "orange", size=0.4)+ labs(y = expression(paste("Dissolved Oxygen (mg ", L^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

Temp.fig2019 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=temp.water), color = "red", size=0.4)+ labs(y = expression(paste("Temperature (°C", ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )

q.fig2019 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 9000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


#L.fig <- moos.comb  %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(moos.comb$light))


panGPP <- ggplotGrob(gpp2019)
panDO <- ggplotGrob(DO.fig2019)
panTemp <- ggplotGrob(Temp.fig2019)
panQ <- ggplotGrob(q.fig2019)


grid::grid.newpage()
grid.draw(rbind(panGPP, panDO, panQ,panTemp, size="max"))
fig2019 <- arrangeGrob(rbind(panGPP, panDO, panQ,panTemp,size="max"))
ggsave(path = here("plots"), file = "moos2019.gpp.q.pdf", fig2019, width = 12,  height = 6, units = "in", limitsize = FALSE)


```



```{r}
moos.metab <- read.csv(here("outputs", "moose2020-Run_2023-Full.rerun.02.04.csv"))
moos.metab$date <- as.POSIXct(moos.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2020 <- ggplot(data=moos.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 7) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2020", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


moos.comb <- read.csv(here("outputs", "moos.comb.csv"))
moos.comb$solar.time <- as.POSIXct(moos.comb$solar.time, tz = "UTC")

moos.comb$discharge  <- moos.comb$discharge 



q.fig2020 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 9000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )


#L.fig <- moos.comb  %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(moos.comb$light))


panGPP <- ggplotGrob(gpp2020)
 
panQ <- ggplotGrob(q.fig2020)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2020 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "moos2020.gpp.q.pdf", fig2020, width = 12,  height = 6, units = "in", limitsize = FALSE)


```


```{r}
moos.metab <- read.csv(here("outputs", "moose2021-Run_2023-Full.rerun.02.04.csv"))
moos.metab$date <- as.POSIXct(moos.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2021 <- ggplot(data=moos.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 7) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))+ annotation_custom(grobTree(textGrob("2021", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))



moos.comb <- read.csv(here("outputs", "moos.comb.csv"))
moos.comb$solar.time <- as.POSIXct(moos.comb$solar.time, tz = "UTC")

moos.comb$discharge  <- moos.comb$discharge 


q.fig2021 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 9000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))


#L.fig <- moos.comb  %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(moos.comb$light))


panGPP <- ggplotGrob(gpp2021)
 
panQ <- ggplotGrob(q.fig2021)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2021 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "moos2021.gpp.q.pdf", fig2021, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
moos.metab <- read.csv(here("outputs", "moose2022-Run_2023-Full.rerun.02.04.csv"))
moos.metab$date <- as.POSIXct(moos.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2022 <- ggplot(data=moos.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 7) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2022", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


moos.comb <- read.csv(here("outputs", "moos.comb.csv"))
moos.comb$solar.time <- as.POSIXct(moos.comb$solar.time, tz = "UTC")

moos.comb$discharge  <- moos.comb$discharge 


q.fig2022 <-  moos.comb %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 9000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00"))) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )



#L.fig <- moos.comb  %>% filter(datetimeAK >= min(moos.metab$date)) %>% filter(datetimeAK <= max(moos.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(moos.comb$light))


panGPP <- ggplotGrob(gpp2022)
 
panQ <- ggplotGrob(q.fig2022)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "moos2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}

library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)
# If that doesnt do it, add grid

#devtools::install_github("thomasp85/patchwork")
library(patchwork)


plottest <- gpp2019+ggtitle("Moose Creek")+theme(plot.title = element_text(size = 30, hjust = 0)) + gpp2020 + q.fig2019+q.fig2020 + gpp2021+gpp2022+q.fig2021+q.fig2022 + plot_layout(ncol = 2, widths = c(2, 2))

ggsave(path = here("plots"), file = "moos.gpp.q.all.pdf", plottest, width = 11*1.3,  height = 8.5*1.3, units = "in", limitsize = FALSE)



```





```{r}

vaul.metab <- read.csv(here("outputs", "vault2019-Run_2023-Full.rerun.02.04.csv"))
vaul.metab$date <- as.POSIXct(vaul.metab$date)


# grob <- grobTree(textGrob("2019", x="2019-09-01", y=4, hjust=0,
#   gp=gpar(col="black", fontsize=20, fontface="italic")))
# Plo





gpp2019 <- ggplot(data=vaul.metab, aes(x=(date), y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+ annotate("text", x= as.POSIXct("2019-09-11"), y=max(vaul.metab$GPP_mean),label="2019")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ annotation_custom(grobTree(textGrob("2019", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))









vaul.comb <- read.csv(here("outputs", "vaul.comb.csv"))
vaul.comb$solar.time <- as.POSIXct(vaul.comb$solar.time, tz = "UTC")

vaul.comb$discharge  <- vaul.comb$discharge 


q.fig2019 <-  vaul.comb %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


#L.fig <- vaul.comb  %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$light))


panGPP <- ggplotGrob(gpp2019)
 
panQ <- ggplotGrob(q.fig2019)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2019 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "vaul2019.gpp.q.pdf", fig2019, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
vaul.metab <- read.csv(here("outputs", "vault2020-Run_2023-Full.rerun.02.04.csv"))
vaul.metab$date <- as.POSIXct(vaul.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2020 <- ggplot(data=vaul.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2020", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


vaul.comb <- read.csv(here("outputs", "vaul.comb.csv"))
vaul.comb$solar.time <- as.POSIXct(vaul.comb$solar.time, tz = "UTC")

vaul.comb$discharge  <- vaul.comb$discharge 



q.fig2020 <-  vaul.comb %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )


#L.fig <- vaul.comb  %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$light))


panGPP <- ggplotGrob(gpp2020)
 
panQ <- ggplotGrob(q.fig2020)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2020 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "vaul2020.gpp.q.pdf", fig2020, width = 12,  height = 6, units = "in", limitsize = FALSE)


```


```{r}
vaul.metab <- read.csv(here("outputs", "vault2021-2022-Run_2023-Full.rerun.02.04.csv")) %>% filter(date<"2022-01-01")
vaul.metab$date <- as.POSIXct(vaul.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2021 <- ggplot(data=vaul.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))+ annotation_custom(grobTree(textGrob("2021", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))



vaul.comb <- read.csv(here("outputs", "vaul.comb.csv"))
vaul.comb$solar.time <- as.POSIXct(vaul.comb$solar.time, tz = "UTC")

vaul.comb$discharge  <- vaul.comb$discharge 


q.fig2021 <-  vaul.comb %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))


#L.fig <- vaul.comb  %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$light))


panGPP <- ggplotGrob(gpp2021)
 
panQ <- ggplotGrob(q.fig2021)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2021 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "vaul2021.gpp.q.pdf", fig2021, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
vaul.metab <- read.csv(here("outputs", "vault2021-2022-Run_2023-Full.rerun.02.04.csv")) %>% filter(date>"2022-01-01")
vaul.metab$date <- as.POSIXct(vaul.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2022 <- ggplot(data=vaul.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2022", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


vaul.comb <- read.csv(here("outputs", "vaul.comb.csv"))
vaul.comb$solar.time <- as.POSIXct(vaul.comb$solar.time, tz = "UTC")

vaul.comb$discharge  <- vaul.comb$discharge 


q.fig2022 <-  vaul.comb %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 15000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00"))) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )



#L.fig <- vaul.comb  %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$light))


panGPP <- ggplotGrob(gpp2022)
 
panQ <- ggplotGrob(q.fig2022)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "vaul2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}

library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)
# If that doesnt do it, add grid

#devtools::install_github("thomasp85/patchwork")
library(patchwork)


plottest <- gpp2019+ggtitle("Vault Creek")+theme(plot.title = element_text(size = 30, hjust = 0)) + gpp2020 + q.fig2019+q.fig2020 + gpp2021+gpp2022+q.fig2021+q.fig2022 + plot_layout(ncol = 2, widths = c(2, 2))

ggsave(path = here("plots"), file = "vaul.gpp.q.all.pdf", plottest, width = 11*1.3,  height = 8.5*1.3, units = "in", limitsize = FALSE)



```

```{r}

poke.metab <- read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv"))
poke.metab$date <- as.POSIXct(poke.metab$date)


# grob <- grobTree(textGrob("2019", x="2019-09-01", y=4, hjust=0,
#   gp=gpar(col="black", fontsize=20, fontface="italic")))
# Plo





gpp2019 <- ggplot(data=poke.metab, aes(x=(date), y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+ annotate("text", x= as.POSIXct("2019-09-11"), y=max(poke.metab$GPP_mean),label="2019")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ annotation_custom(grobTree(textGrob("2019", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))









poke.comb <- read.csv(here("outputs", "poke.comb.csv"))
poke.comb$solar.time <- as.POSIXct(poke.comb$solar.time, tz = "UTC")

poke.comb$discharge  <- poke.comb$discharge 


q.fig2019 <-  poke.comb %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


#L.fig <- poke.comb  %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(poke.comb$light))


panGPP <- ggplotGrob(gpp2019)
 
panQ <- ggplotGrob(q.fig2019)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2019 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "poke2019.gpp.q.pdf", fig2019, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
poke.metab <- read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv"))
poke.metab$date <- as.POSIXct(poke.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2020 <- ggplot(data=poke.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2020", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


poke.comb <- read.csv(here("outputs", "poke.comb.csv"))
poke.comb$solar.time <- as.POSIXct(poke.comb$solar.time, tz = "UTC")

poke.comb$discharge  <- poke.comb$discharge 



q.fig2020 <-  poke.comb %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )


#L.fig <- poke.comb  %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(poke.comb$light))


panGPP <- ggplotGrob(gpp2020)
 
panQ <- ggplotGrob(q.fig2020)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2020 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "poke2020.gpp.q.pdf", fig2020, width = 12,  height = 6, units = "in", limitsize = FALSE)


```


```{r}
poke.metab <- read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv"))
poke.metab$date <- as.POSIXct(poke.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2021 <- ggplot(data=poke.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))+ annotation_custom(grobTree(textGrob("2021", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))



poke.comb <- read.csv(here("outputs", "poke.comb.csv"))
poke.comb$solar.time <- as.POSIXct(poke.comb$solar.time, tz = "UTC")

poke.comb$discharge  <- poke.comb$discharge 


q.fig2021 <-  poke.comb %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))


#L.fig <- poke.comb  %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(poke.comb$light))


panGPP <- ggplotGrob(gpp2021)
 
panQ <- ggplotGrob(q.fig2021)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2021 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "poke2021.gpp.q.pdf", fig2021, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
poke.metab <- read.csv(here("outputs", "poker2022-Run_2023-Full.rerun.02.04.csv")) %>% filter(date>"2040-01-01")
poke.metab$date <- as.POSIXct(poke.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2022 <- ggplot(data=poke.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 4) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2022", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


poke.comb <- read.csv(here("outputs", "poke.comb.csv"))
poke.comb$solar.time <- as.POSIXct(poke.comb$solar.time, tz = "UTC")

poke.comb$discharge  <- poke.comb$discharge 


q.fig2022 <-  poke.comb %>%  ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 3000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00"))) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )



#L.fig <- poke.comb  %>% filter(datetimeAK >= min(poke.metab$date)) %>% filter(datetimeAK <= max(poke.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(poke.comb$light))


panGPP <- ggplotGrob(gpp2022)
 
panQ <- ggplotGrob(q.fig2022)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "poke2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}

library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)
# If that doesnt do it, add grid

#devtools::install_github("thomasp85/patchwork")
library(patchwork)


plottest <- gpp2019+ggtitle("Poker Creek")+theme(plot.title = element_text(size = 30, hjust = 0)) + gpp2020 + q.fig2019+q.fig2020 + gpp2021+gpp2022+q.fig2021 +q.fig2022+ plot_layout(ncol = 2, widths = c(2, 2))

ggsave(path = here("plots"), file = "poke.gpp.q.all.pdf", plottest, width = 11*1.3,  height = 8.5*1.3, units = "in", limitsize = FALSE)



```


```{r}

strt.metab <- read.csv(here("outputs", "stuart2019-Run_2023-Full.rerun.02.04.csv"))
strt.metab$date <- as.POSIXct(strt.metab$date)


# grob <- grobTree(textGrob("2019", x="2019-09-01", y=4, hjust=0,
#   gp=gpar(col="black", fontsize=20, fontface="italic")))
# Plo





gpp2019 <- ggplot(data=strt.metab, aes(x=(date), y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 5)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+ annotate("text", x= as.POSIXct("2019-09-11"), y=max(strt.metab$GPP_mean),label="2019")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ annotation_custom(grobTree(textGrob("2019", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))









strt.comb <- read.csv(here("outputs", "strt.comb.csv"))
strt.comb$solar.time <- as.POSIXct(strt.comb$solar.time, tz = "UTC")

strt.comb$discharge  <- strt.comb$discharge 


q.fig2019 <-  strt.comb %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = as.POSIXct(solar.time))) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 15000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) +scale_x_datetime(limits = ymd_hm(c("2019-05-25 00:00", "2019-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )


#L.fig <- strt.comb  %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(strt.comb$light))


panGPP <- ggplotGrob(gpp2019)
 
panQ <- ggplotGrob(q.fig2019)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2019 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "strt2019.gpp.q.pdf", fig2019, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
strt.metab <- read.csv(here("outputs", "stuart2020-Run_2023-Full.rerun.02.04.csv"))
strt.metab$date <- as.POSIXct(strt.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2020 <- ggplot(data=strt.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 5) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2020", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


strt.comb <- read.csv(here("outputs", "strt.comb.csv"))
strt.comb$solar.time <- as.POSIXct(strt.comb$solar.time, tz = "UTC")

strt.comb$discharge  <- strt.comb$discharge 



q.fig2020 <-  strt.comb %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 15000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2020-05-25 00:00", "2020-10-15 00:00")))+theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )


#L.fig <- strt.comb  %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(strt.comb$light))


panGPP <- ggplotGrob(gpp2020)
 
panQ <- ggplotGrob(q.fig2020)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2020 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "strt2020.gpp.q.pdf", fig2020, width = 12,  height = 6, units = "in", limitsize = FALSE)


```


```{r}
strt.metab <- read.csv(here("outputs", "stuart2021-Run_2023-Full.rerun.02.04.csv"))
strt.metab$date <- as.POSIXct(strt.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2021 <- ggplot(data=strt.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 5) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))+ annotation_custom(grobTree(textGrob("2021", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))



strt.comb <- read.csv(here("outputs", "strt.comb.csv"))
strt.comb$solar.time <- as.POSIXct(strt.comb$solar.time, tz = "UTC")

strt.comb$discharge  <- strt.comb$discharge 


q.fig2021 <-  strt.comb %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 15000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2021-05-25 00:00", "2021-10-15 00:00")))


#L.fig <- strt.comb  %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(strt.comb$light))


panGPP <- ggplotGrob(gpp2021)
 
panQ <- ggplotGrob(q.fig2021)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2021 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "strt2021.gpp.q.pdf", fig2021, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}
strt.metab <- read.csv(here("outputs", "stuart2022-Run_2023-Full.rerun.02.04.csv"))
strt.metab$date <- as.POSIXct(strt.metab$date)

labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec')

gpp2022 <- ggplot(data=strt.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, 5) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00")))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ annotation_custom(grobTree(textGrob("2022", x=0.8, hjust=0, y=0.8, vjust=0, gp=gpar(col="black", fontsize=30))))


strt.comb <- read.csv(here("outputs", "strt.comb.csv"))
strt.comb$solar.time <- as.POSIXct(strt.comb$solar.time, tz = "UTC")

strt.comb$discharge  <- strt.comb$discharge 


q.fig2022 <-  strt.comb %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, 15000)+theme(axis.title.x=element_blank())+theme(text = element_text(size=20))+scale_x_datetime(limits = ymd_hm(c("2022-05-25 00:00", "2022-10-15 00:00"))) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )



#L.fig <- strt.comb  %>% filter(datetimeAK >= min(strt.metab$date)) %>% filter(datetimeAK <= max(strt.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(strt.comb$light))


panGPP <- ggplotGrob(gpp2022)
 
panQ <- ggplotGrob(q.fig2022)
grid::grid.newpage()
grid.draw(rbind(panGPP,  panQ,size="max"))
fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max"))
ggsave(path = here("plots"), file = "strt2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE)


```

```{r}

library(grid)
library(ggeffects)
library(gridExtra)
library(gtable)
# If that doesnt do it, add grid

#devtools::install_github("thomasp85/patchwork")
library(patchwork)


plottest <- gpp2019+ggtitle("Stuart Creek")+theme(plot.title = element_text(size = 30, hjust = 0)) + gpp2020 + q.fig2019+q.fig2020 + gpp2021+gpp2022+q.fig2021+q.fig2022 + plot_layout(ncol = 2, widths = c(2, 2))

ggsave(path = here("plots"), file = "strt.gpp.q.all.pdf", plottest, width = 11*1.3,  height = 8.5*1.3, units = "in", limitsize = FALSE)



```






#Combine ############################ Metab All Plots ############################ 


```{r}
strt.gpp <- rbind( read.csv(here("outputs", "stuart2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2022-Run_2023-Full.rerun.02.04.csv")))
strt.gpp$site = "STRT"
strt.gpp$PF = "High"
strt.gpp$burn = "Burned"
strt.gpp$year <- format(as.Date(strt.gpp$date, format="%Y-%m-%d"),"%Y")




vaul.gpp <- rbind( read.csv(here("outputs", "vault2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2021-2022-Run_2023-Full.rerun.02.04.csv")))
vaul.gpp$site = "VAUL"
vaul.gpp$PF = "High"
vaul.gpp$burn = "Unburned"
vaul.gpp$year <- format(as.Date(vaul.gpp$date, format="%Y-%m-%d"),"%Y")



#Poker 2022 bad
poke.gpp <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")))

poke.gpp$site = "POKE"
poke.gpp$PF = "Low"
poke.gpp$burn = "Burned"
poke.gpp$year <- format(as.Date(poke.gpp$date, format="%Y-%m-%d"),"%Y")



frch.gpp <- rbind( read.csv(here("outputs", "french2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2021-Run_2023-Full.rerun.02.04.csv")),read.csv(here("outputs", "french2022-Run_2023-Full.rerun.02.04.csv")))
frch.gpp$site = "FRCH"
frch.gpp$PF = "Low"
frch.gpp$burn = "Unburned"
frch.gpp$year <- format(as.Date(frch.gpp$date, format="%Y-%m-%d"),"%Y")




moos.gpp <- rbind(
  read.csv(here("outputs", "moose2019-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs","moose2021-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2022-Run_2023-Full.rerun.02.04.csv"))
  )
moos.gpp$site = "MOOS"
moos.gpp$PF = "Low"
moos.gpp$burn = "Burned"
moos.gpp$year <- format(as.Date(moos.gpp$date, format="%Y-%m-%d"),"%Y")



cari.gpp <- rbind( read.csv(here("outputs", "caribou2019-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2020-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2021-Run_2023-Full.03.08.csv")))

ts_cari <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(moos.gpp$date)), by = '1 days'))))
cari.gpp.ts <- full_join(cari.gpp, ts_cari, by = "date")

cari.gpp.ts$site = "CARI"
cari.gpp.ts$PF = "Low"
cari.gpp.ts$burn = "Unburned"
cari.gpp.ts$year <- format(as.Date(cari.gpp.ts$date, format="%Y-%m-%d"),"%Y")















craw.gpp <- read.csv(here("outputs", "crawford2019-Run_2023-FC.02.22.csv"))



ts_craw <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(craw.gpp$date)), by = '1 days'))))
craw.gpp.ts <- full_join(craw.gpp, ts_craw, by = "date")
craw.gpp.ts$site = "CRAW"
craw.gpp.ts$PF = "High"
craw.gpp.ts$burn = "Burned"
craw.gpp.ts$year <- format(as.Date(craw.gpp.ts$date, format="%Y-%m-%d"),"%Y")



mast.gpp <- read.csv(here("outputs", "mastodon2019-Run_2023-FC-rerun.02.02.csv"))


ts_mast <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(mast.gpp$date)), by = '1 days'))))
mast.gpp.ts <- full_join(mast.gpp, ts_mast, by = "date")
mast.gpp.ts$site = "MAST"
mast.gpp.ts$PF = "High"
mast.gpp.ts$burn = "Burned"
mast.gpp.ts$year <- format(as.Date(mast.gpp.ts$date, format="%Y-%m-%d"),"%Y")




shov.gpp <- read.csv(here("outputs", "shovel2019-Run_2023-FC.02.12.csv"))

ts_shov <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(shov.gpp$date)), by = '1 days'))))
shov.gpp.ts <- full_join(shov.gpp, ts_shov, by = "date")
shov.gpp.ts$site = "SHOV"
shov.gpp.ts$PF = "High"
shov.gpp.ts$burn = "Burned"
shov.gpp.ts$year <- format(as.Date(shov.gpp.ts$date, format="%Y-%m-%d"),"%Y")



#combine
metab_all <- rbind(strt.gpp, vaul.gpp, poke.gpp, frch.gpp, moos.gpp,cari.gpp.ts,craw.gpp.ts,mast.gpp.ts,shov.gpp.ts)

metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)



write.csv(metab_all_stw, here("outputs", "metab.all.csv"))
write.csv(metab_all_stw, here("outputs", "DoD_metab_TS.csv"))


median(na.omit(metab_all_stw$GPP_mean))
mean(na.omit(metab_all_stw$GPP_mean))


library(ggpattern)

plot2019 <- metab_all_stw %>% filter(year=="2019")%>%  ggplot(aes(x=site, y=GPP_mean)) + facet_wrap(~year, nrow = 2, dir = "v")+ geom_boxplot(aes(fill=as.factor(PF)),show.legend = FALSE) +
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(0,12)+ggtitle("2019")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))

plot2020 <- metab_all_stw %>% filter(year=="2020")%>%  ggplot(aes(x=site, y=GPP_mean)) + facet_wrap(~year, nrow = 2, dir = "v") + geom_boxplot(aes(fill=as.factor(PF)))+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(0,12)+ggtitle("2020")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"), labels=c('High Permafrost', 'Low Permafrost'))+  theme(legend.title=element_blank())+theme(axis.title.x=element_blank() )+  theme(legend.title=element_blank())+theme(legend.position = c(0.7, 0.7))

plot2021 <- metab_all_stw %>% filter(year=="2021")%>%  ggplot(aes(x=site, y=GPP_mean)) + facet_wrap(~year, nrow = 2, dir = "v") + geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ylim(0,12)+ggtitle("2021")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(axis.title.x=element_blank() )

poke.gpp <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2022-Run_2023-Full.rerun.02.04.csv")))

poke.gpp$site = "POKE"
poke.gpp$PF = "Low"
poke.gpp$burn = "Burned"
poke.gpp$year <- format(as.Date(poke.gpp$date, format="%Y-%m-%d"),"%Y")

poke.gpp$GPP_mean <- NA

metab_all <- rbind(strt.gpp, vaul.gpp, poke.gpp, frch.gpp, moos.gpp,cari.gpp.ts, craw.gpp.ts,mast.gpp.ts,shov.gpp.ts) 

# write.csv(metab_all, here("outputs","metab.all.csv"))

metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)


plot2022 <- metab_all_stw %>% filter(year=="2022")%>%  ggplot(aes(x=site, y=GPP_mean)) + facet_wrap(~year, nrow = 2, dir = "v") +  geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ylim(0,12)+ggtitle("2022")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+theme(axis.title.x=element_blank() )

library("RColorBrewer") 
library(patchwork)

plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)

pdf(here('plots',"GPP.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()

pdf(("C:/Users/jacob/OneDrive - University of Alaska/GitHub/MetabolismStorage/Plots/GPP_Boxplots/GPP.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()



```


#Combine

```{r}
strt.er <- rbind( read.csv(here("outputs", "stuart2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2022-Run_2023-Full.rerun.02.04.csv")))
strt.er$site = "STRT"
strt.er$PF = "High"
strt.er$burn = "Burned"
strt.er$year <- format(as.Date(strt.er$date, format="%Y-%m-%d"),"%Y")




vaul.er <- rbind( read.csv(here("outputs", "vault2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2021-2022-Run_2023-Full.rerun.02.04.csv")))
vaul.er$site = "VAUL"
vaul.er$PF = "High"
vaul.er$burn = "Unburned"
vaul.er$year <- format(as.Date(vaul.er$date, format="%Y-%m-%d"),"%Y")



#Poker 2022 bad
poke.er <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")))

poke.er$site = "POKE"
poke.er$PF = "Low"
poke.er$burn = "Burned"
poke.er$year <- format(as.Date(poke.er$date, format="%Y-%m-%d"),"%Y")



frch.er <- rbind( read.csv(here("outputs", "french2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2021-Run_2023-Full.rerun.02.04.csv")),read.csv(here("outputs", "french2022-Run_2023-Full.rerun.02.04.csv")))
frch.er$site = "FRCH"
frch.er$PF = "Low"
frch.er$burn = "Unburned"
frch.er$year <- format(as.Date(frch.er$date, format="%Y-%m-%d"),"%Y")




moos.er <- rbind(
  read.csv(here("outputs", "moose2019-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs","moose2021-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2022-Run_2023-Full.rerun.02.04.csv"))
  )
moos.er$site = "MOOS"
moos.er$PF = "Low"
moos.er$burn = "Burned"
moos.er$year <- format(as.Date(moos.er$date, format="%Y-%m-%d"),"%Y")



cari.er <- rbind( read.csv(here("outputs", "caribou2019-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2020-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2021-Run_2023-Full.03.08.csv")))

ts_cari <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(moos.er$date)), by = '1 days'))))
cari.er.ts <- full_join(cari.er, ts_cari, by = "date")

cari.er.ts$site = "CARI"
cari.er.ts$PF = "Low"
cari.er.ts$burn = "Unburned"
cari.er.ts$year <- format(as.Date(cari.er.ts$date, format="%Y-%m-%d"),"%Y")















craw.er <- read.csv(here("outputs", "crawford2019-Run_2023-FC.02.22.csv"))



ts_craw <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(craw.er$date)), by = '1 days'))))
craw.er.ts <- full_join(craw.er, ts_craw, by = "date")
craw.er.ts$site = "CRAW"
craw.er.ts$PF = "High"
craw.er.ts$burn = "Burned"
craw.er.ts$year <- format(as.Date(craw.er.ts$date, format="%Y-%m-%d"),"%Y")



mast.er <- read.csv(here("outputs", "mastodon2019-Run_2023-FC-rerun.02.02.csv"))


ts_mast <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(mast.er$date)), by = '1 days'))))
mast.er.ts <- full_join(mast.er, ts_mast, by = "date")
mast.er.ts$site = "MAST"
mast.er.ts$PF = "High"
mast.er.ts$burn = "Burned"
mast.er.ts$year <- format(as.Date(mast.er.ts$date, format="%Y-%m-%d"),"%Y")




shov.er <- read.csv(here("outputs", "shovel2019-Run_2023-FC.02.12.csv"))

ts_shov <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(shov.er$date)), by = '1 days'))))
shov.er.ts <- full_join(shov.er, ts_shov, by = "date")
shov.er.ts$site = "SHOV"
shov.er.ts$PF = "High"
shov.er.ts$burn = "Burned"
shov.er.ts$year <- format(as.Date(shov.er.ts$date, format="%Y-%m-%d"),"%Y")



#combine
metab_all <- rbind(strt.er, vaul.er, poke.er, frch.er, moos.er,cari.er.ts,craw.er.ts,mast.er.ts,shov.er.ts)

metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)



write.csv(metab_all_stw, here("outputs", "metab.all.csv"))
write.csv(metab_all_stw, here("outputs", "DoD_metab_TS.csv"))


median(na.omit(metab_all_stw$er_mean))
mean(na.omit(metab_all_stw$er_mean))


library(ggpattern)

plot2019 <- metab_all_stw %>% filter(year=="2019")%>%  ggplot(aes(x=site, y=ER_mean)) + facet_wrap(~year, nrow = 2, dir = "v")+ geom_boxplot(aes(fill=as.factor(PF)),show.legend = FALSE) +
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(-50,0)+ggtitle("2019")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("ER (g ", O[2] ," ", m^-2, d^-1, ")")))


plot2020 <- metab_all_stw %>% filter(year=="2020")%>%  ggplot(aes(x=site, y=ER_mean)) + facet_wrap(~year, nrow = 2, dir = "v") + geom_boxplot(aes(fill=as.factor(PF)))+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(-50,0)+ggtitle("2020")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"), labels=c('High Permafrost', 'Low Permafrost'))+  theme(legend.title=element_blank())+theme(axis.title.x=element_blank() )+  theme(legend.title=element_blank())+theme(legend.position = c(0.7, 0.7))

plot2021 <- metab_all_stw %>% filter(year=="2021")%>%  ggplot(aes(x=site, y=ER_mean)) + facet_wrap(~year, nrow = 2, dir = "v") + geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ylim(-50,0)+ggtitle("2021")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("er (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(axis.title.x=element_blank() )

poke.er <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2022-Run_2023-Full.rerun.02.04.csv")))

poke.er$site = "POKE"
poke.er$PF = "Low"
poke.er$burn = "Burned"
poke.er$year <- format(as.Date(poke.er$date, format="%Y-%m-%d"),"%Y")

poke.er$ER_mean <- NA

metab_all <- rbind(strt.er, vaul.er, poke.er, frch.er, moos.er,cari.er.ts, craw.er.ts,mast.er.ts,shov.er.ts) 

# write.csv(metab_all, here("outputs","metab.all.csv"))

metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)


plot2022 <- metab_all_stw %>% filter(year=="2022")%>%  ggplot(aes(x=site, y=ER_mean)) + facet_wrap(~year, nrow = 2, dir = "v") +  geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ylim(-50,0)+ggtitle("2022")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+theme(axis.title.x=element_blank() )

library("RColorBrewer") 
library(patchwork)

plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)

pdf(here('plots',"er.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()

pdf(("C:/Users/jacob/OneDrive - University of Alaska/GitHub/MetabolismStorage/Plots/er_Boxplots/er.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()



```

```{r}

strt.nep <- rbind( read.csv(here("outputs", "stuart2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "stuart2022-Run_2023-Full.rerun.02.04.csv")))
strt.nep$site = "STRT"
strt.nep$PF = "High"
strt.nep$burn = "Burned"
strt.nep$year <- format(as.Date(strt.nep$date, format="%Y-%m-%d"),"%Y")




vaul.nep <- rbind( read.csv(here("outputs", "vault2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "vault2021-2022-Run_2023-Full.rerun.02.04.csv")))
vaul.nep$site = "VAUL"
vaul.nep$PF = "High"
vaul.nep$burn = "Unburned"
vaul.nep$year <- format(as.Date(vaul.nep$date, format="%Y-%m-%d"),"%Y")



#poker 2022 bad
poke.nep <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")))

poke.nep$site = "POKE"
poke.nep$PF = "Low"
poke.nep$burn = "Burned"
poke.nep$year <- format(as.Date(poke.nep$date, format="%Y-%m-%d"),"%Y")



frch.nep <- rbind( read.csv(here("outputs", "french2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "french2021-Run_2023-Full.rerun.02.04.csv")),read.csv(here("outputs", "french2022-Run_2023-Full.rerun.02.04.csv")))
frch.nep$site = "FRCH"
frch.nep$PF = "Low"
frch.nep$burn = "Unburned"
frch.nep$year <- format(as.Date(frch.nep$date, format="%Y-%m-%d"),"%Y")



moos.nep <- rbind(
  read.csv(here("outputs", "moose2019-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs","moose2021-Run_2023-Full.rerun.02.04.csv")),
  read.csv(here("outputs", "moose2022-Run_2023-Full.rerun.02.04.csv"))
  )
moos.nep$site = "MOOS"
moos.nep$PF = "Low"
moos.nep$burn = "Burned"
moos.nep$year <- format(as.Date(moos.nep$date, format="%Y-%m-%d"),"%Y")


cari.nep <- rbind( read.csv(here("outputs", "caribou2019-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2020-Run_2023-Full.03.08.csv")), read.csv(here("outputs", "caribou2021-Run_2023-Full.03.08.csv")))

ts_cari <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(moos.nep$date)), by = '1 days'))))
cari.nep.ts <- full_join(cari.nep, ts_cari, by = "date")

cari.nep.ts$site = "CARI"
cari.nep.ts$PF = "Low"
cari.nep.ts$burn = "Unburned"
cari.nep.ts$year <- format(as.Date(cari.nep.ts$date, format="%Y-%m-%d"),"%Y")





craw.nep <- read.csv(here("outputs", "crawford2019-Run_2023-FC.02.22.csv"))



ts_craw <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(craw.nep$date)), by = '1 days'))))
craw.nep.ts <- full_join(craw.nep, ts_craw, by = "date")
craw.nep.ts$site = "CRAW"
craw.nep.ts$PF = "High"
craw.nep.ts$burn = "Burned"
craw.nep.ts$year <- format(as.Date(craw.nep.ts$date, format="%Y-%m-%d"),"%Y")



mast.nep <- read.csv(here("outputs", "mastodon2019-Run_2023-FC-rerun.02.02.csv"))


ts_mast <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(mast.nep$date)), by = '1 days'))))
mast.nep.ts <- full_join(mast.nep, ts_mast, by = "date")
mast.nep.ts$site = "MAST"
mast.nep.ts$PF = "High"
mast.nep.ts$burn = "Burned"
mast.nep.ts$year <- format(as.Date(mast.nep.ts$date, format="%Y-%m-%d"),"%Y")




shov.nep <- read.csv(here("outputs", "shovel2019-Run_2023-FC.02.12.csv"))

ts_shov <- data.frame(date = as.character(as.POSIXct(seq(ymd("2019-04-15"),ymd(max(shov.nep$date)), by = '1 days'))))
shov.nep.ts <- full_join(shov.nep, ts_shov, by = "date")
shov.nep.ts$site = "SHOV"
shov.nep.ts$PF = "High"
shov.nep.ts$burn = "Burned"
shov.nep.ts$year <- format(as.Date(shov.nep.ts$date, format="%Y-%m-%d"),"%Y")



#combine
metab_all <- rbind(strt.nep, vaul.nep, poke.nep, frch.nep, moos.nep, cari.nep.ts, craw.nep.ts,mast.nep.ts,shov.nep.ts) 


metab_all$NEP_mean <- metab_all$GPP_mean+metab_all$ER_mean

metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)


library(ggpattern)

plot2019 <- metab_all_stw %>% filter(year=="2019")%>%  ggplot(aes(x=site, y=NEP_mean)) + facet_wrap(~year, nrow = 2, dir = "v") +geom_hline(yintercept=0,linetype=2)+geom_boxplot(aes(fill=as.factor(PF)),show.legend = FALSE) +
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(-25,10)+ggtitle("2019")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("NEP (g ", O[2] ," ", m^-2, d^-1, ")")))

plot2020 <- metab_all_stw %>% filter(year=="2020")%>%  ggplot(aes(x=site, y=NEP_mean)) + facet_wrap(~year, nrow = 2, dir = "v")  +geom_hline(yintercept=0,linetype=2)+geom_boxplot(aes(fill=as.factor(PF)))+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ theme( strip.background = element_blank(),strip.text.x = element_blank() )+ylim(-25,10)+ggtitle("2020")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"), labels=c('High Permafrost', 'Low Permafrost'))+  theme(legend.title=element_blank())+theme(legend.position = c(0.7, 0.9))+ guides(color=guide_legend(override.aes=list(fill=NA)))

plot2021 <- metab_all_stw %>% filter(year=="2021")%>%  ggplot(aes(x=site, y=NEP_mean)) + facet_wrap(~year, nrow = 2, dir = "v")+geom_hline(yintercept=0,linetype=2) + geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ylim(-25,10)+ggtitle("2021")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+labs(y = expression(paste("NEP (g ", O[2] ," ", m^-2, d^-1, ")")))+theme(axis.title.x=element_blank() )

poke.nep <- rbind( read.csv(here("outputs", "poker2019-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2020-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2021-Run_2023-Full.rerun.02.04.csv")), read.csv(here("outputs", "poker2022-Run_2023-Full.rerun.02.04.csv")))

poke.nep$site = "POKE"
poke.nep$PF = "Low"
poke.nep$burn = "Burned"
poke.nep$year <- format(as.Date(poke.nep$date, format="%Y-%m-%d"),"%Y")

poke.nep$NEP_mean <- NA

strt.nep$NEP_mean <- strt.nep$GPP_mean+strt.nep$ER_mean
vaul.nep$NEP_mean <- vaul.nep$GPP_mean+vaul.nep$ER_mean
moos.nep$NEP_mean <- moos.nep$GPP_mean+moos.nep$ER_mean
frch.nep$NEP_mean <- frch.nep$GPP_mean+frch.nep$ER_mean
cari.nep.ts$NEP_mean <- cari.nep.ts$GPP_mean+cari.nep.ts$ER_mean
craw.nep.ts$NEP_mean <- craw.nep.ts$GPP_mean+craw.nep.ts$ER_mean
mast.nep.ts$NEP_mean <- mast.nep.ts$GPP_mean+mast.nep.ts$ER_mean
shov.nep.ts$NEP_mean <- shov.nep.ts$GPP_mean+shov.nep.ts$ER_mean


metab_all <- rbind(strt.nep, vaul.nep, poke.nep, frch.nep,cari.nep.ts,moos.nep,craw.nep.ts,mast.nep.ts,shov.nep.ts) 


metab_all$DOY <- yday(as.POSIXct(metab_all$date))

#highest minimum for all years 
metab_all.2019 <-metab_all %>% filter(year =="2019") %>% filter(DOY>= "167" & DOY<="274")
metab_all.2020 <-metab_all %>% filter(year =="2020") %>% filter(DOY>= "169" & DOY<="276")
metab_all.2021 <-metab_all %>% filter(year =="2021") %>% filter(DOY>= "163" & DOY<="270")
metab_all.2022 <-metab_all %>% filter(year =="2022") %>% filter(DOY>= "164" & DOY<="271")

metab_all_stw <- rbind(metab_all.2019, metab_all.2020, metab_all.2021, metab_all.2022)


plot2022 <- metab_all_stw %>% filter(year=="2022")%>%  ggplot(aes(x=site, y=NEP_mean)) + facet_wrap(~year, nrow = 2, dir = "v") +geom_hline(yintercept=0,linetype=2)+ geom_boxplot(aes(fill=as.factor(PF)), show.legend = FALSE)+
  facet_grid(. ~ burn , space="free_x", scales="free_x", switch="x") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill=NA, colour="grey50"),
        panel.spacing.x=unit(0,"cm"))+ theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank() )+ylim(-25,10)+ggtitle("2022")+theme(plot.title = element_text(hjust = 1))+scale_fill_manual(values = c("#71A6D2", "#A13D2D"))+theme(axis.title.x=element_blank() )

library(patchwork)
NEP_plot <- plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)

pdf(here('plots',"NEP.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()

pdf(("C:/Users/jacob/OneDrive - University of Alaska/GitHub/MetabolismStorage/Plots/NEP_Boxplots/NEP.plot.pdf"), height = 8*1.2, width = 8*1.2)
plot_layout(plot2019+plot2020+plot2021+plot2022, nrow=2, ncol = 2)
dev.off()




```
<!-- ```{r} -->
<!-- vaul.metab <- read.csv(here("outputs", "vault2022-Run_2023-Full.rerun.02.04.csv")) -->
<!-- vaul.metab$date <- as.POSIXct(vaul.metab$date) -->

<!-- labels <- c(light='PAR\n(umol m^-2 s^-1)', discharge= 'm^3/sec') -->

<!-- gpp <- ggplot(data=vaul.metab, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")+ labs(y = expression(paste("GPP (g ", O[2] ," ", m^-2, d^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ ggtitle("Vault Creek, 2022")+theme(plot.title = element_text(hjust = 0.5))+theme(plot.title = element_text(size = 20, face = "bold")) +ylim(0, max(vaul.metab$GPP_mean)) + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) -->



<!-- vaul.comb <- read.csv(here("outputs", "vaul.comb.csv")) -->
<!-- vaul.comb$solar.time <- as.POSIXct(vaul.comb$solar.time, tz = "UTC") -->

<!-- vaul.comb$discharge  <- vaul.comb$discharge  -->


<!-- q.fig <-  vaul.comb %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=discharge), color = "slateblue4", size=0.4)+ labs(y = expression(paste("Discharge (L ", s^-1, ")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$discharge))+theme(axis.title.x=element_blank())+theme(text = element_text(size=20)) -->

<!-- #L.fig <- vaul.comb  %>% filter(datetimeAK >= min(vaul.metab$date)) %>% filter(datetimeAK <= max(vaul.metab$date)) %>% ggplot(aes(x = solar.time)) +geom_point(aes(y=light), color = "orange", size=0.4)+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ labs(y = expression(paste("PAR (umol ", m^-2, s^-1,")")))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())+ theme(panel.border = element_rect(colour = "black", fill=NA, size=2))+theme( axis.title.y = element_text(size = 20))+theme(axis.text.y=element_text(size=20))+ylim(0, max(vaul.comb$light)) -->


<!-- panGPP <- ggplotGrob(gpp) -->
<!--   -->
<!-- panQ <- ggplotGrob(q.fig) -->
<!-- grid::grid.newpage() -->
<!-- grid.draw(rbind(panGPP,  panQ,size="max")) -->
<!-- fig2022 <- arrangeGrob(rbind(panGPP,  panQ,size="max")) -->
<!-- ggsave(path = here("plots"), file = "vaul2022.gpp.q.pdf", fig2022, width = 12,  height = 6, units = "in", limitsize = FALSE) -->


<!-- ``` -->

Light Fill for TKH

#French light
```{r}

frch.data <- read.csv(here("outputs", "frch.comb.csv"))

frch.data.2022 <- frch.data %>% filter(datetimeAK>"2022-05-11 13:30:00")

frch.data.2022 <-  frch.data.2022 %>% filter(datetimeAK<"2022-10-10 10:00:00")

frch.light.2022 <- frch.data.2022 %>% select(light,datetimeAK)
frch.light.2022$site = "FRCH"



frch.data <- read.csv(here("outputs", "frch.comb.csv"))

frch.data.2021 <- frch.data %>% filter(datetimeAK>"2021-01-01"&datetimeAK<"2021-12-01")

frch.data.2021 <-  frch.data.2021 %>% filter(datetimeAK<"2021-09-28 10:15:00")

frch.light.2021 <- frch.data.2021 %>% select(light,datetimeAK)
frch.light.2021$site = "FRCH"


frch.data <- read.csv(here("outputs", "frch.comb.csv"))

frch.data.2020 <- frch.data %>% filter(datetimeAK>"2020-01-01"&datetimeAK<"2020-12-01")

frch.data.2020 <-  frch.data.2020 %>% filter(datetimeAK<"2020-10-15 09:15:00")

frch.light.2020 <- frch.data.2020 %>% select(light,datetimeAK)
frch.light.2020$site = "FRCH"


frch.data <- read.csv(here("outputs", "frch.comb.csv"))

frch.data.2019 <- frch.data %>% filter(datetimeAK>"2019-01-01"&datetimeAK<"2019-12-01")
frch.data.2019 <-  frch.data.2019 %>% filter(datetimeAK>"2019-04-29 12:30:00" &datetimeAK<"2019-10-10 09:15:00")


frch.light.2019 <- frch.data.2019 %>% select(light,datetimeAK)
frch.light.2019$site = "FRCH"



frch.light <- rbind(frch.light.2019,frch.light.2020,frch.light.2021,frch.light.2022)

frch.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

frch.light$light <- na_kalman(frch.light$light)

frch.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()


```

#Moose Light
```{r}

moos.data <- read.csv(here("outputs", "moos.comb.csv"))

moos.data.2022 <- moos.data %>% filter(datetimeAK>"2022-01-01")

#FILL with Met Tower Light 
CRREL <- read.csv(here("MetTowerData.csv"), skip = 5)

CRREL$datetimeAK <- as.POSIXct(CRREL$Time, tz = "America/Anchorage")
CRREL <- CRREL %>% rename(ParWm2 = CPCRW.CRREL.Main.Met.Station..PAR_Den_AVG.W.m2.)


#### POKE 2022 ####
PAR.2022.url <- "https://drive.google.com/drive/u/1/folders/1JW8NRBDT-I9oIOayp3i4kGef9cP3nO3k"
PAR_2022.prt1 <- drive_get(as_id(PAR.2022.url))
poke_par_glist <- drive_ls(PAR_2022.prt1, pattern = "220606_11619_125_POKE.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2022.Data1 <- read.csv("220606_11619_125_POKE.CSV",
                               skip = 9, header = FALSE)
poke.par.2022.Data1 <- poke.par.2022.Data1 %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)


poke_par_glist <- drive_ls(PAR_2022.prt1, pattern = "220801_11619_125_POKE.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2022.Data2 <- read.csv("220801_11619_125_POKE.CSV",
                               skip = 9, header = FALSE)
poke.par.2022.Data2 <- poke.par.2022.Data2 %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)

poke_par_glist <- drive_ls(PAR_2022.prt1, pattern = "221007_11619_125_POKE.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2022.Data3 <- read.csv("221007_11619_125_POKE.CSV",
                               skip = 9, header = FALSE)
poke.par.2022.Data3 <- poke.par.2022.Data3 %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)


poke.par.2022.Data <- rbind(poke.par.2022.Data1, poke.par.2022.Data2, poke.par.2022.Data3)


#Fix Date Time
poke.par.2022.Data$DateTime <- paste(poke.par.2022.Data$Date, poke.par.2022.Data$Time, sep="")

poke.par.2022.Data$DateTime <-  dmy_hms(poke.par.2022.Data$DateTime)
poke.par.2022.Data$DateTime <- force_tz(poke.par.2022.Data$DateTime, "America/Anchorage")

#Calibrate logger 11619 to LICOR
poke.par.2022.Data$CalibratedValue <- poke.par.2022.Data$CalibratedValue * 0.035


poke.par.2022.Data$DateTime <-  lubridate::round_date(poke.par.2022.Data$DateTime, "15 minutes")

poke.par.2022.Data <- poke.par.2022.Data %>% filter(DateTime>="2022-05-09 13:30:00")




#2022
moos.data.2022$datetimeAK <- as.POSIXct(moos.data.2022$datetimeAK, tz = "America/Anchorage")

CRREL_MOOS.2022 <- left_join(moos.data.2022,CRREL, by = "datetimeAK")

CRREL_MOOS.2022 <- fill(CRREL_MOOS.2022, ParWm2, .direction = c("down"))
                               
max.par.poke.2022 <- max( na.omit(as.numeric(poke.par.2022.Data$CalibratedValue) ))

max.par.crrel.2022 <- max(na.omit(CRREL_MOOS.2022$ParWm2))

multiplyFactor.2022 <- max.par.poke.2022/max.par.crrel.2022


CRREL_MOOS.2022$ParMetCor <- CRREL_MOOS.2022$ParWm2 *multiplyFactor.2022


CRREL_MOOS.2022.fill <- CRREL_MOOS.2022 %>% 
  mutate(light = coalesce(light,ParMetCor))



CRREL_MOOS.2022.fill %>% ggplot(aes(x=datetimeAK, y=light))+geom_point()




moos.light.2022 <- CRREL_MOOS.2022.fill %>% select(light,datetimeAK)
moos.light.2022$site = "MOOS"

moos.light.2022$datetimeAK <- as.character(moos.light.2022$datetimeAK)


moos.data <- read.csv(here("outputs", "moos.comb.csv"))

moos.data.2021 <- moos.data %>% filter(datetimeAK>"2021-05-05 17:15:00"&datetimeAK<"2021-09-28 13:45:00")

moos.light.2021 <- moos.data.2021 %>% select(light,datetimeAK)
moos.light.2021$site = "MOOS"
moos.light.2021$datetimeAK <- as.POSIXct(moos.light.2021$datetimeAK, tz = "America/Anchorage")


moos.data <- read.csv(here("outputs", "moos.comb.csv"))

moos.data.2020 <- moos.data %>% filter(datetimeAK>"2020-06-10 14:30:00"&datetimeAK<"2020-12-01")

moos.light.2020 <- moos.data.2020 %>% select(light,datetimeAK)
moos.light.2020$site = "MOOS"
moos.light.2020$datetimeAK <- as.POSIXct(moos.light.2020$datetimeAK, tz = "America/Anchorage")


moos.data <- read.csv(here("outputs", "moos.comb.csv"))

moos.data.2019 <- moos.data %>% filter(datetimeAK>"2019-05-09 12:00:00"&datetimeAK<"2019-10-22 07:30:00")


moos.light.2019 <- moos.data.2019 %>% select(light,datetimeAK)
moos.light.2019$site = "MOOS"
moos.light.2019$datetimeAK <- as.POSIXct(moos.light.2019$datetimeAK, tz = "America/Anchorage")



moos.light <- rbind(moos.light.2019,moos.light.2020,moos.light.2021,moos.light.2022)
moos.light$datetimeAK <- as.POSIXct(moos.light$datetimeAK, tz = "America/Anchorage")

moos.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

moos.light$light <- na_kalman(moos.light$light)

moos.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

```



#Stuart Light

```{r}

strt.data <- read.csv(here("outputs", "strt.comb.csv"))

strt.data.2022 <- strt.data %>% filter(datetimeAK>"2022-06-02 16:15:00" & datetimeAK <"2022-10-08 14:00:00")

strt.light.2022 <- strt.data.2022 %>% select(light,datetimeAK)

strt.light.2022$datetimeAK <- as.POSIXct(strt.light.2022$datetimeAK, tz = "America/Anchorage")

strt.light.2022$site = "STRT"



strt.data <- read.csv(here("outputs", "strt.comb.csv"))

strt.data.2021 <- strt.data %>% filter(datetimeAK>"2021-01-05 17:15:00"&datetimeAK<"2021-09-30 11:45:00")

strt.light.2021 <- strt.data.2021 %>% select(light,datetimeAK)
strt.light.2021$site = "STRT"
strt.light.2021$datetimeAK <- as.POSIXct(strt.light.2021$datetimeAK, tz = "America/Anchorage")


strt.data <- read.csv(here("outputs", "strt.comb.csv"))

strt.data.2020 <- strt.data %>% filter(datetimeAK>"2020-06-17 16:45:00"&datetimeAK<"2020-10-13 13:30:00")

strt.light.2020 <- strt.data.2020 %>% select(light,datetimeAK)
strt.light.2020$site = "STRT"
strt.light.2020$datetimeAK <- as.POSIXct(strt.light.2020$datetimeAK, tz = "America/Anchorage")






# NEEDS MET TOWER FILL 
strt.data <- read.csv(here("outputs", "strt.comb.csv"))
strt.data.2019 <- strt.data %>% filter(datetimeAK>"2019-01-09 12:00:00"&datetimeAK<"2019-10-16 10:15:00")

strt.light.2019 <- strt.data.2019 %>% select(light,datetimeAK)
strt.light.2019$site = "STRT"
strt.light.2019$datetimeAK <- as.POSIXct(strt.light.2019$datetimeAK, tz = "America/Anchorage")


strt.light.2019 =  strt.light.2019 %>% mutate(light= ifelse(datetimeAK >= '2019-08-23 14:15:00' & datetimeAK <= '2019-09-17 12:00:00',NA, light))



CRREL_STRT.2019 <- left_join(strt.light.2019,CRREL, by = "datetimeAK")

CRREL_STRT.2019 <- fill(CRREL_STRT.2019, ParWm2, .direction = c("down"))







#### POKE 2019 ####
PAR.2019.url <- "https://drive.google.com/drive/u/1/folders/11kWuwCF6pTXYolwYnxcsX6OcYyQeF35z"
PAR_19.prt1 <- drive_get(as_id(PAR.2019.url))
poke_par_glist <- drive_ls(PAR_19.prt1, pattern = "191017_11619_POKE.CSV")
walk(poke_par_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
poke.par.2019.Data <- read.csv("191017_11619_POKE.CSV",
                               skip = 8, header = FALSE)
poke.par.2019.Data <- poke.par.2019.Data %>%
  dplyr::rename(ScanNumber = V1, Date = V2, Time = V3, RawValue = V4, CalibratedValue = V5)

#Fix Date Time
poke.par.2019.Data$DateTime <- paste(poke.par.2019.Data$Date, poke.par.2019.Data$Time, sep="")

poke.par.2019.Data$DateTime <-  dmy_hms(poke.par.2019.Data$DateTime)
poke.par.2019.Data$DateTime <- force_tz(poke.par.2019.Data$DateTime, "America/Anchorage")

#Calibrate logger 11619 to LICOR
poke.par.2019.Data$CalibratedValue <- poke.par.2019.Data$CalibratedValue * 0.035


max.par.poke.2019 <- max(poke.par.2019.Data$CalibratedValue)

max.par.crrel.2019 <- max(CRREL_STRT.2019$ParWm2)

multiplyFactor.2019 <- max.par.poke.2019/max.par.crrel.2019


CRREL_STRT.2019$ParMetCor <- CRREL_STRT.2019$ParWm2 *multiplyFactor.2019


CRREL_STRT.2019 <- CRREL_STRT.2019 %>% 
  mutate(light = coalesce(light,ParMetCor))


CRREL_STRT.2019 %>% ggplot(aes(x=datetimeAK, y=light))+geom_point()
CRREL_STRT.2019$site = "STRT"


strt.light.2019 <- CRREL_STRT.2019 %>% select(datetimeAK, light, site)


strt.light <- rbind(strt.light.2019,strt.light.2020,strt.light.2021,strt.light.2022)
strt.light$datetimeAK <- as.POSIXct(strt.light$datetimeAK, tz = "America/Anchorage")

strt.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

strt.light$light <- na_kalman(strt.light$light)

strt.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

```





#Poker

```{r}

poke.data <- read.csv(here("outputs", "poke.comb.csv"))

poke.data.2022 <- poke.data %>% filter(datetimeAK>"2022-05-09 13:00:00")

poke.data.2022 <-  poke.data.2022 %>% filter(datetimeAK<"2022-10-07 10:15:00")

poke.light.2022 <- poke.data.2022 %>% select(light,datetimeAK)
poke.light.2022$site = "POKE"


# POKE FILL MET END OF DATA 
poke.data <- read.csv(here("outputs", "poke.comb.csv"))

poke.data.2021 <- poke.data %>% filter(datetimeAK>"2021-01-01"&datetimeAK<"2021-09-27 16:00:00")

poke.data.2021 <-  poke.data.2021 %>% filter(datetimeAK>"2021-05-06 17:15:00")

poke.data.2021$datetimeAK <- as.POSIXct(poke.data.2021$datetimeAK, tz = "America/Anchorage")

###### 2021 #####
PAR.2021.url <- "https://drive.google.com/drive/u/1/folders/1EPjHLDmfbCo5n12AKj7QpN2vXRCPQtg5"
PAR_2021.prt1 <- drive_get(as_id(PAR.2021.url))
par2021_glist <- drive_ls(PAR_2021.prt1, pattern = "all.dates.par.2021.csv")
walk(par2021_glist$id, ~ drive_download(as_id(.x), overwrite = TRUE))
par2021.Data <- read.csv("all.dates.par.2021.csv",
                         skip = 0, header = TRUE)
# Sort into sites
poke.par2021.Data <- par2021.Data %>% filter(site == "poke")

poke.par2021.Data <- poke.par2021.Data %>%
  dplyr::rename(RawValue = V5)

poke.par2021.Data$DateTime <- as.POSIXct(poke.par2021.Data$DateTime)

#Calibrate loggers to LICOR
poke.par2021.Data$Calibrated.Value <- poke.par2021.Data$Calibrated.Value * 0.035



#2021
CRREL_POKE.2021 <- left_join(poke.data.2021,CRREL, by = "datetimeAK")

CRREL_POKE.2021 <- fill(CRREL_POKE.2021, ParWm2, .direction = c("down"))


max.par.poke.2021 <- max(na.omit(poke.par2021.Data$Calibrated.Value))

max.par.crrel.2021 <- max(na.omit(CRREL_POKE.2021$ParWm2))

multiplyFactor.2021 <- max.par.poke.2021/max.par.crrel.2021


CRREL_POKE.2021$ParMetCor <- CRREL_POKE.2021$ParWm2 *multiplyFactor.2021


CRREL_POKE.2021 <- CRREL_POKE.2021 %>% 
  mutate(light = coalesce(light,ParMetCor))



CRREL_POKE.2021 %>% ggplot(aes(x=datetimeAK, y=light))+geom_point()







poke.light.2021 <- CRREL_POKE.2021 %>% select(light,datetimeAK)
poke.light.2021$datetimeAK <- as.character(poke.light.2021$datetimeAK)

poke.light.2021$site = "POKE"






poke.data <- read.csv(here("outputs", "poke.comb.csv"))

poke.data.2020 <- poke.data %>% filter(datetimeAK>"2020-06-04 13:15:00"&datetimeAK<"2020-12-01")

poke.data.2020 <-  poke.data.2020 %>% filter(datetimeAK<"2020-10-14 14:00:00")

poke.light.2020 <- poke.data.2020 %>% select(light,datetimeAK)
poke.light.2020$site = "POKE"



poke.data <- read.csv(here("outputs", "poke.comb.csv"))

poke.data.2019 <- poke.data %>% filter(datetimeAK>"2019-05-14 11:45:00"&datetimeAK<"2019-10-17 11:30:00")


poke.light.2019 <- poke.data.2019 %>% select(light,datetimeAK)
poke.light.2019$site = "POKE"



poke.light <- rbind(poke.light.2019,poke.light.2020,poke.light.2021,poke.light.2022)

poke.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

poke.light$light <- na_kalman(poke.light$light)

poke.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()


```



Vault


Light Fill for TKH

```{r}

vaul.data <- read.csv(here("outputs", "vaul.comb.csv"))



vaul.data.2022 <- vaul.data %>% filter(datetimeAK>"2022-05-17 13:07:36")

vaul.data.2022 <-  vaul.data.2022 %>% filter(datetimeAK<"2022-10-11 23:45:00")
vaul.data.2022$datetimeAK <- lubridate::round_date(as.POSIXct(vaul.data.2022$datetimeAK, tz = "America/Anchorage"), "15 minutes") 
vaul.data.2022$datetimeAK <- as.character(vaul.data.2022$datetimeAK)


vaul.light.2022 <- (vaul.data.2022) %>% select(light,datetimeAK)
vaul.light.2022 <- na.omit(vaul.light.2022)

ts_2022.vaul <- data.frame(datetimeAK = force_tz(as.POSIXct(seq(ymd_hm("2022-05-17 13:30"),ymd_hm("2022-10-11 23:30"), by = '15 mins')), tz = "America/Anchorage"))

ts_2022.vaul$datetimeAK <- as.character(ts_2022.vaul$datetimeAK)

vaul.light.2022 <- full_join(vaul.light.2022, ts_2022.vaul, by = "datetimeAK")

vaul.light.2022$site = "VAUL"



vaul.data <- read.csv(here("outputs", "vaul.comb.csv"))

vaul.data.2021 <- vaul.data %>% filter(datetimeAK>"2021-05-10 17:15:00"&datetimeAK<"2021-09-27 16:00:00")


vaul.light.2021 <- vaul.data.2021 %>% select(light,datetimeAK)
vaul.light.2021$site = "VAUL"


vaul.data <- read.csv(here("outputs", "vaul.comb.csv"))

vaul.data.2020 <- vaul.data %>% filter(datetimeAK>"2020-06-05 15:30:00"&datetimeAK<"2020-10-14 13:30:00")

vaul.light.2020 <- vaul.data.2020 %>% select(light,datetimeAK)
vaul.light.2020$site = "VAUL"


vaul.data <- read.csv(here("outputs", "vaul.comb.csv"))

vaul.data.2019 <- vaul.data %>% filter(datetimeAK>"2019-01-01"&datetimeAK<"2019-12-01")
vaul.data.2019 <-  vaul.data.2019 %>% filter(datetimeAK>"2019-04-29 12:30:00" &datetimeAK<"2019-10-16 23:45:00")


vaul.light.2019 <- vaul.data.2019 %>% select(light,datetimeAK)
vaul.light.2019$site = "VAUL"



vaul.light <- rbind(vaul.light.2019,vaul.light.2020,vaul.light.2021,vaul.light.2022)

vaul.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()

vaul.light$light <- na_kalman(vaul.light$light)

vaul.light %>% ggplot(aes(x=as.POSIXct(datetimeAK, tz = "America/Anchorage"), y= light))+geom_miss_point()


```

Combine

```{r}

strt.light$datetimeAK <- as.character(strt.light$datetimeAK)
moos.light$datetimeAK <- as.character(moos.light$datetimeAK)

light.data.full <- rbind(vaul.light, poke.light, strt.light, moos.light, frch.light)

write.csv(light.data.full, here("outputs","light.data.all.years.csv"))

```





# ```{r}
# 
# Suna.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2019/processed_sensor_dat/SUNA.EXO.int.corr.lab_2019.csv")
# 
# 
# 
# Suna.data$datetimeAK <- as.POSIXct(Suna.data$datetimeAK, tz = "America/Anchorage")
# 
# Suna.data$date <- as.Date(Suna.data$datetimeAK)
# 
# avg_data.suna <- Suna.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2019
# 
# moos.2019.suna <- avg_data.suna %>% select(date,Site, nitrateuM.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "MOOS")
# 
# 
# metab_all.suna.moos.19 <- full_join(moos.metab.19,moos.2019.suna, by="date")
# 
# 
# 
# #strt 2019
# 
# strt.2019.suna <- avg_data.suna %>% select(date,Site, nitrateuM.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "STRT")
# 
# 
# metab_all.suna.strt.19 <- full_join(strt.metab.19,strt.2019.suna, by="date")
# 
# 
# 
# 
# #frch 2019
# 
# frch.2019.suna <- avg_data.suna %>% select(date,Site, nitrateuM.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "FRCH")
# 
# 
# metab_all.suna.frch.19 <- full_join(frch.metab.19,frch.2019.suna, by="date")
# 
# 
# #VAUL 2019
# 
# VAUL.2019.suna <- avg_data.suna %>% select(date,Site, nitrateuM.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "VAUL")
# 
# 
# metab_all.suna.VAUL.19 <- full_join(VAUL.metab.19,VAUL.2019.suna, by="date")
# 
# 
# 
# #POKE 2019
# 
# POKE.2019.suna <- avg_data.suna %>% select(date,Site, nitrateuM.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "POKE")
# 
# 
# metab_all.suna.POKE.19 <- full_join(POKE.metab.19,POKE.2019.suna, by="date")
# 
# 
# 
# Gpp_no3_moos_19.plot <- metab_all.suna.moos.19 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 19")
# 
# Gpp_no3_strt_19.plot <- metab_all.suna.strt.19 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 19")
# 
# 
# Gpp_no3_frch_19.plot <- metab_all.suna.frch.19 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 19")
# 
# 
# Gpp_no3_vaul_19.plot <- metab_all.suna.VAUL.19 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 19")
# 
# 
# Gpp_no3_poke_19.plot <- metab_all.suna.POKE.19 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 19")
# 
# 
# 
# 
# 
# ```
# 
# 
# ```{r}
# 
# Suna.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2020/processed_sensor_dat/SUNA.EXO.int.corr.lab_2020.csv")
# 
# 
# 
# Suna.data$datetimeAK <- as.POSIXct(Suna.data$datetimeAK, tz = "America/Anchorage")
# 
# Suna.data$date <- as.Date(Suna.data$datetimeAK)
# 
# avg_data.suna <- Suna.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2020
# 
# moos.2020.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "MOOS")
# 
# 
# metab_all.suna.moos.20 <- full_join(moos.metab.20,moos.2020.suna, by="date")
# 
# metab_all.suna.moos.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 20")
# 
# #strt 2020
# 
# strt.2020.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "STRT")
# 
# 
# metab_all.suna.strt.20 <- full_join(strt.metab.20,strt.2020.suna, by="date")
# 
# metab_all.suna.strt.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 20")
# 
# 
# 
# 
# #frch 2020
# 
# frch.2020.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "FRCH")
# 
# 
# metab_all.suna.frch.20 <- full_join(frch.metab.20,frch.2020.suna, by="date")
# 
# metab_all.suna.frch.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 20")
# 
# #VAUL 2020
# 
# VAUL.2020.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "VAUL")
# 
# 
# metab_all.suna.VAUL.20 <- full_join(VAUL.metab.20,VAUL.2020.suna, by="date")
# 
# metab_all.suna.VAUL.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 20")
# 
# 
# #POKE 2020
# 
# POKE.2020.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "POKE")
# 
# 
# metab_all.suna.POKE.20 <- full_join(POKE.metab.20,POKE.2020.suna, by="date")
# 
# metab_all.suna.POKE.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 20")
# 
# 
# 
# Gpp_no3_moos_20.plot <- metab_all.suna.moos.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 20")
# 
# Gpp_no3_strt_20.plot <- metab_all.suna.strt.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 20")
# 
# 
# Gpp_no3_frch_20.plot <- metab_all.suna.frch.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 20")
# 
# 
# Gpp_no3_vaul_20.plot <- metab_all.suna.VAUL.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 20")
# 
# 
# Gpp_no3_poke_20.plot <- metab_all.suna.POKE.20 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 20")
# 
# 
# 
# 
# ```
# 
# 
# ```{r}
# 
# Suna.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2021/processed_sensor_dat/SUNA.EXO.int.corr.lab_2021.csv")
# 
# 
# 
# Suna.data$datetimeAK <- as.POSIXct(Suna.data$datetimeAK, tz = "America/Anchorage")
# 
# Suna.data$date <- as.Date(Suna.data$datetimeAK)
# 
# avg_data.suna <- Suna.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2021
# 
# moos.2021.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "MOOS")
# 
# 
# metab_all.suna.moos.21 <- full_join(moos.metab.21,moos.2021.suna, by="date")
# 
# metab_all.suna.moos.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 21")
# 
# #strt 2021
# 
# strt.2021.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "STRT")
# 
# 
# metab_all.suna.strt.21 <- full_join(strt.metab.21,strt.2021.suna, by="date")
# 
# metab_all.suna.strt.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 21")
# 
# 
# 
# 
# #frch 2021
# 
# frch.2021.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "FRCH")
# 
# 
# metab_all.suna.frch.21 <- full_join(frch.metab.21,frch.2021.suna, by="date")
# 
# metab_all.suna.frch.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 21")
# 
# #VAUL 2021
# 
# VAUL.2021.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "VAUL")
# 
# 
# metab_all.suna.VAUL.21 <- full_join(VAUL.metab.21,VAUL.2021.suna, by="date")
# 
# metab_all.suna.VAUL.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 21")
# 
# 
# #POKE 2021
# 
# POKE.2021.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "POKE")
# 
# 
# metab_all.suna.POKE.21 <- full_join(POKE.metab.21,POKE.2021.suna, by="date")
# 
# metab_all.suna.POKE.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 21")
# 
# 
# 
# 
# Gpp_no3_moos_21.plot <- metab_all.suna.moos.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 21")
# 
# Gpp_no3_strt_21.plot <- metab_all.suna.strt.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 21")
# 
# 
# Gpp_no3_frch_21.plot <- metab_all.suna.frch.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 21")
# 
# 
# Gpp_no3_vaul_21.plot <- metab_all.suna.VAUL.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 21")
# 
# 
# Gpp_no3_poke_21.plot <- metab_all.suna.POKE.21 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 21")
# 
# 
# ```
# 
# 
# 
# 
# ```{r}
# 
# Suna.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2022/processed_sensor_dat/SUNA.EXO.int.corr.lab_2022.csv")
# 
# 
# 
# Suna.data$datetimeAK <- as.POSIXct(Suna.data$datetimeAK, tz = "America/Anchorage")
# 
# Suna.data$date <- as.Date(Suna.data$datetimeAK)
# 
# avg_data.suna <- Suna.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2022
# 
# moos.2022.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "MOOS")
# 
# 
# metab_all.suna.moos.22 <- full_join(moos.metab.22,moos.2022.suna, by="date")
# 
# metab_all.suna.moos.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 22")
# 
# #strt 2022
# 
# strt.2022.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "STRT")
# 
# 
# metab_all.suna.strt.22 <- full_join(strt.metab.22,strt.2022.suna, by="date")
# 
# metab_all.suna.strt.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 22")
# 
# 
# 
# 
# #frch 2022
# 
# frch.2022.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "FRCH")
# 
# 
# metab_all.suna.frch.22 <- full_join(frch.metab.22,frch.2022.suna, by="date")
# 
# metab_all.suna.frch.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 22")
# 
# #VAUL 2022
# 
# VAUL.2022.suna <- avg_data.suna %>% select(date,Site, nitrateuM.adj.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "VAUL")
# 
# 
# metab_all.suna.VAUL.22 <- full_join(VAUL.metab.22,VAUL.2022.suna, by="date")
# 
# metab_all.suna.VAUL.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 22")
# 
# 
# 
# Gpp_no3_moos_22.plot <- metab_all.suna.moos.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 22")
# 
# Gpp_no3_strt_22.plot <- metab_all.suna.strt.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 22")
# 
# 
# Gpp_no3_frch_22.plot <- metab_all.suna.frch.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 22")
# 
# 
# Gpp_no3_vaul_22.plot <- metab_all.suna.VAUL.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 22")
# 
# 
# Gpp_no3_poke_22.plot <- metab_all.suna.POKE.22 %>% ggplot(aes(x=GPP_mean, y=nitrateuM.adj.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 22")
# 
# 
# ```
# 
# 
# 
# ```{r}
# 
# 
# ggarrange(Gpp_no3_moos_19.plot ,Gpp_no3_strt_19.plot, Gpp_no3_frch_19.plot, Gpp_no3_vaul_19.plot, Gpp_no3_poke_19.plot, Gpp_no3_moos_20.plot, Gpp_no3_strt_20.plot, Gpp_no3_frch_20.plot, Gpp_no3_vaul_20.plot, Gpp_no3_poke_20.plot,  Gpp_no3_moos_21.plot, Gpp_no3_strt_21.plot,Gpp_no3_frch_21.plot,Gpp_no3_vaul_21.plot, Gpp_no3_poke_21.plot, Gpp_no3_moos_22.plot,Gpp_no3_strt_22.plot,Gpp_no3_frch_22.plot,Gpp_no3_vaul_22.plot)
# 
# 
# 
# ```
# 
# 
# 
# 
# ```{r}
# 
# EXO.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2019/processed_sensor_dat/SUNA.EXO.int.corr.lab_2019.csv")
# 
# 
# 
# EXO.data$datetimeAK <- as.POSIXct(EXO.data$datetimeAK, tz = "America/Anchorage")
# 
# EXO.data$date <- as.Date(EXO.data$datetimeAK)
# 
# avg_data.EXO <- EXO.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2019
# 
# moos.2019.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "MOOS")
# 
# 
# metab_all.EXO.moos.19 <- full_join(moos.metab.19,moos.2019.EXO, by="date")
# 
# metab_all.EXO.moos.19 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 19")
# 
# #strt 2019
# 
# strt.2019.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "STRT")
# 
# 
# metab_all.EXO.strt.19 <- full_join(strt.metab.19,strt.2019.EXO, by="date")
# 
# metab_all.EXO.strt.19 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 19")
# 
# 
# 
# 
# #frch 2019
# 
# frch.2019.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "FRCH")
# 
# 
# metab_all.EXO.frch.19 <- full_join(frch.metab.19,frch.2019.EXO, by="date")
# 
# metab_all.EXO.frch.19 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 19")
# 
# #VAUL 2019
# 
# VAUL.2019.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "VAUL")
# 
# 
# metab_all.EXO.VAUL.19 <- full_join(VAUL.metab.19,VAUL.2019.EXO, by="date")
# 
# metab_all.EXO.VAUL.19 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 19")
# 
# 
# #POKE 2019
# 
# POKE.2019.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.19 <- metab_all %>% filter(format(date, format = "%Y")== "2019" & site == "POKE")
# 
# 
# metab_all.EXO.POKE.19 <- full_join(POKE.metab.19,POKE.2019.EXO, by="date")
# 
# metab_all.EXO.POKE.19 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 19")
# 
# 
# 
# 
# 
# ```
# 
# 
# ```{r}
# 
# EXO.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2020/processed_sensor_dat/SUNA.EXO.int.corr.lab_2020.csv")
# 
# 
# 
# EXO.data$datetimeAK <- as.POSIXct(EXO.data$datetimeAK, tz = "America/Anchorage")
# 
# EXO.data$date <- as.Date(EXO.data$datetimeAK)
# 
# avg_data.EXO <- EXO.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2020
# 
# moos.2020.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "MOOS")
# 
# 
# metab_all.EXO.moos.20 <- full_join(moos.metab.20,moos.2020.EXO, by="date")
# 
# metab_all.EXO.moos.20 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 20")
# 
# #strt 2020
# 
# strt.2020.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "STRT")
# 
# 
# metab_all.EXO.strt.20 <- full_join(strt.metab.20,strt.2020.EXO, by="date")
# 
# metab_all.EXO.strt.20 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 20")
# 
# 
# 
# 
# #frch 2020
# 
# frch.2020.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "FRCH")
# 
# 
# metab_all.EXO.frch.20 <- full_join(frch.metab.20,frch.2020.EXO, by="date")
# 
# metab_all.EXO.frch.20 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 20")
# 
# #VAUL 2020
# 
# VAUL.2020.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "VAUL")
# 
# 
# metab_all.EXO.VAUL.20 <- full_join(VAUL.metab.20,VAUL.2020.EXO, by="date")
# 
# metab_all.EXO.VAUL.20 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 20")
# 
# 
# #POKE 2020
# 
# POKE.2020.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.20 <- metab_all %>% filter(format(date, format = "%Y")== "2020" & site == "POKE")
# 
# 
# metab_all.EXO.POKE.20 <- full_join(POKE.metab.20,POKE.2020.EXO, by="date")
# 
# metab_all.EXO.POKE.20 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 20")
# 
# 
# 
# 
# 
# ```
# 
# 
# ```{r}
# 
# EXO.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2021/processed_sensor_dat/SUNA.EXO.int.corr.lab_2021.csv")
# 
# 
# 
# EXO.data$datetimeAK <- as.POSIXct(EXO.data$datetimeAK, tz = "America/Anchorage")
# 
# EXO.data$date <- as.Date(EXO.data$datetimeAK)
# 
# avg_data.EXO <- EXO.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2021
# 
# moos.2021.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "MOOS")
# 
# 
# metab_all.EXO.moos.21 <- full_join(moos.metab.21,moos.2021.EXO, by="date")
# 
# metab_all.EXO.moos.21 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 21")
# 
# #strt 2021
# 
# strt.2021.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "STRT")
# 
# 
# metab_all.EXO.strt.21 <- full_join(strt.metab.21,strt.2021.EXO, by="date")
# 
# metab_all.EXO.strt.21 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 21")
# 
# 
# 
# 
# #frch 2021
# 
# frch.2021.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "FRCH")
# 
# 
# metab_all.EXO.frch.21 <- full_join(frch.metab.21,frch.2021.EXO, by="date")
# 
# metab_all.EXO.frch.21 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 21")
# 
# #VAUL 2021
# 
# VAUL.2021.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "VAUL")
# 
# 
# metab_all.EXO.VAUL.21 <- full_join(VAUL.metab.21,VAUL.2021.EXO, by="date")
# 
# metab_all.EXO.VAUL.21 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 21")
# 
# 
# #POKE 2021
# 
# POKE.2021.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="POKE")
# 
# metab_all$date <- as.Date(metab_all$date)
# POKE.metab.21 <- metab_all %>% filter(format(date, format = "%Y")== "2021" & site == "POKE")
# 
# 
# metab_all.EXO.POKE.21 <- full_join(POKE.metab.21,POKE.2021.EXO, by="date")
# 
# metab_all.EXO.POKE.21 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("POKE 21")
# 
# 
# 
# 
# 
# ```
# 
# 
# 
# 
# ```{r}
# 
# EXO.data <- read.csv("C:/Users/jacob/OneDrive - University of Alaska/GitHub/DoD_2022/processed_sensor_dat/SUNA.EXO.int.corr.lab_2022.csv")
# 
# 
# 
# EXO.data$datetimeAK <- as.POSIXct(EXO.data$datetimeAK, tz = "America/Anchorage")
# 
# EXO.data$date <- as.Date(EXO.data$datetimeAK)
# 
# avg_data.EXO <- EXO.data %>% 
#   group_by(date, Site) %>% 
#   summarise(across(where(is.numeric), mean, na.rm = TRUE))
# 
# #moos 2022
# 
# moos.2022.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="MOOS")
# 
# metab_all$date <- as.Date(metab_all$date)
# moos.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "MOOS")
# 
# 
# metab_all.EXO.moos.22 <- full_join(moos.metab.22,moos.2022.EXO, by="date")
# 
# metab_all.EXO.moos.22 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("MOOS 22")
# 
# #strt 2022
# 
# strt.2022.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="STRT")
# 
# metab_all$date <- as.Date(metab_all$date)
# strt.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "STRT")
# 
# 
# metab_all.EXO.strt.22 <- full_join(strt.metab.22,strt.2022.EXO, by="date")
# 
# metab_all.EXO.strt.22 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("STRT 22")
# 
# 
# 
# 
# #frch 2022
# 
# frch.2022.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="FRCH")
# 
# metab_all$date <- as.Date(metab_all$date)
# frch.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "FRCH")
# 
# 
# metab_all.EXO.frch.22 <- full_join(frch.metab.22,frch.2022.EXO, by="date")
# 
# metab_all.EXO.frch.22 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("FRCH 22")
# 
# #VAUL 2022
# 
# VAUL.2022.EXO <- avg_data.EXO %>% select(date,Site, fDOM.QSU.mn) %>% filter(Site=="VAUL")
# 
# metab_all$date <- as.Date(metab_all$date)
# VAUL.metab.22 <- metab_all %>% filter(format(date, format = "%Y")== "2022" & site == "VAUL")
# 
# 
# metab_all.EXO.VAUL.22 <- full_join(VAUL.metab.22,VAUL.2022.EXO, by="date")
# 
# metab_all.EXO.VAUL.22 %>% ggplot(aes(x=ER_mean, y=fDOM.QSU.mn))+geom_point()+stat_poly_eq()+ggtitle("VAUL 22")
# 
# 
# 
# 
# ```


