---
title: "PrettyMoosMetab"
author: "Jacob"
date: "11/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libs, warning=FALSE, message=FALSE}
library(ggpubr)
library(anytime)
library(googlesheets4)
library(ggpmisc)
library(plyr)
library(dplyr)
library(lubridate)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(scales)
library(zoo)
library(xts)
library(forecast)
library(googledrive)
library(streamMetabolizer)
library(readr)
library(here)
library(rstan)
library(imputeTS)
library(itsmr)
library(purrr)
library(naniar)
library(data.table)
library(grid)
```

#Metab 2019
```{r}

bayes_name <- mm_name(type='bayes', pool_K600='binned', err_obs_iid=TRUE, err_proc_iid=TRUE)
bayes_name_AppEtAL <- "b_Kb_oipi_tr_plrckm.stan"
bayes_specs <- specs(bayes_name, 
                     burnin_steps=10000, saved_steps=5000, n_cores=4, n_chains = 4, GPP_daily_lower = 0, ER_daily_upper = 0
)

```

```{r fig.width=8, fig.height=10}

data.moos.mm.all <- read.csv(here("outputs", "moose.comb.readyforMetab.new.clean.csv"))

data.moos.mm.all <- data.moos.mm.all %>% filter(solar.time <= "2019-07-14 04:13:57")

data.moos.mm.all <- data.moos.mm.all %>%  rename(DO.sat = DO.sat.EXO)
data.moos.mm.all$solar.time <- as.POSIXct(data.moos.mm.all$solar.time, tz = "UTC")
data.moos.mm.all <- data.moos.mm.all %>% select(solar.time, DO.obs, DO.sat, light, discharge, depth, temp.water)

startTime <- as.POSIXct(Sys.time())
mm.test.moos <- metab(bayes_specs, data=data.moos.mm.all)
endTime <- as.POSIXct(Sys.time())
# 
difftime(endTime, startTime)
save(mm.test.moos, file = here("Outputs", "moos.2019.1.new.RData"))
# 
fit.moos <- get_fit(mm.test.moos)
fit.daily <- fit.moos$daily
write.csv(fit.daily, here("outputs", "moos.2019.1.new.full.csv"))

```

#Plot Input Data

```{r fig.width = 13, fig.height=7}
model_data <- get_data(mm.test.moos)
write.csv(model_data, here("outputs", "moos.2019.1.new.model_data.csv"))

plot_DO_preds(mm.test.moos)
```

```{r fig.width = 20, fig.height=10}

light.fig <- ggplot(data=model_data, aes(x=solar.time, y=light)) + geom_point(color = "chartreuse4") +theme(text = element_text(size=20))
q.fig<- ggplot(data=model_data, aes(x=solar.time, y=discharge)) + geom_point(color = "darksalmon")+theme(text = element_text(size=20))
temp.fig<- ggplot(data=model_data, aes(x=solar.time, y=temp.water)) + geom_point(color = "turquoise4")+theme(text = element_text(size=20))
depth.fig<- ggplot(data=model_data, aes(x=solar.time, y=depth)) + geom_point(color = "maroon")+theme(text = element_text(size=20))

grid.newpage()
grid.draw(rbind(ggplotGrob(light.fig), ggplotGrob(q.fig),ggplotGrob(depth.fig), ggplotGrob(temp.fig)))

```





```{r fig.width = 10, fig.height=8}
gpp <- ggplot(data=fit.moos$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4")
gpp

#save with no axis for combined plot
gpp <- ggplot(data=fit.moos$daily, aes(x=date, y=GPP_mean)) + geom_point(color = "chartreuse4") + geom_errorbar(aes(ymin=GPP_mean-GPP_sd, ymax=GPP_mean+GPP_sd), width=.2, position=position_dodge(0.05), color = "chartreuse4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )
```

```{r fig.width = 10, fig.height=8}
er <- ggplot(data = fit.daily, aes(x = date)) +geom_point(aes(y = ER_mean), color = "firebrick3") + geom_errorbar(aes(ymin=ER_mean-ER_sd, ymax=ER_mean+ER_sd), width=.2, position=position_dodge(0.05), color = "firebrick3")
er
```

```{r fig.width = 10, fig.height=8}
k600 <- ggplot(data=fit.moos$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange")
k600
#save with no axis for combined plot
k600 <- ggplot(data=fit.moos$daily, aes(x=date, y=K600_daily_mean)) + geom_point(color = "orange") + geom_errorbar(aes(ymin=K600_daily_mean-K600_daily_sd, ymax=K600_daily_mean+K600_daily_sd), width=.2, position=position_dodge(0.05), color = "orange") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )
```

```{r fig.width = 10, fig.height=8}
rhat <- ggplot(data=fit.moos$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + geom_hline(yintercept=1.01, color = "dark blue")+ geom_hline(yintercept=1.1, color = "dark red", linetype = "dashed")
rhat

rhat <- ggplot(data=fit.moos$daily, aes(x=date)) + geom_point(aes(y=GPP_Rhat, colour = "GPP")) + geom_point(aes(y=as.numeric(ER_Rhat), colour = "ER")) + geom_point(aes(y=K600_daily_Rhat, colour = "K600")) +
  labs(y = "RHAT") + theme(legend.position="top") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() )+ geom_hline(yintercept=20, color = "dark blue")
```

```{r fig.width = 10, fig.height=8}
ggplot(data=fit.daily, aes(x=GPP_mean, y=ER_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
```

```{r fig.width = 10, fig.height=8}
ggplot(data=fit.daily, aes(x=GPP_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq() 
```

```{r fig.width = 10, fig.height=8}
ggplot(data=fit.daily, aes(x=ER_mean, y=K600_daily_mean)) + geom_point()+ stat_poly_line() + stat_poly_eq()
```

```{r fig.width = 10, fig.height=10}
mcmc <- get_mcmc(mm.test.moos)
k600mcmc <- rstan::traceplot(mcmc, pars='K600_daily', nrow=7)
k600mcmc
```


```{r fig.width = 10, fig.height=10}
gppmcmc <- rstan::traceplot(mcmc, pars='GPP_daily', nrow=7)
gppmcmc
```

```{r fig.width = 10, fig.height=10}
ermcmc <- rstan::traceplot(mcmc, pars='ER_daily', nrow=7)
ermcmc
```


#DO r2

```{r fig.width = 10, fig.height=8}
moos.DO.pred <- predict_DO(mm.test.moos)
moos.DO.pred <- na.omit(moos.DO.pred)
lm(DO.obs~ DO.mod, data = moos.DO.pred)
moos.DO.pred$SM.date <- as.Date(moos.DO.pred$solar.time - 4*60*60)
moos.DO.pred$SM.date <- as.factor(moos.DO.pred$SM.date)
fit_model <- function(x, y) summary(lm(x ~ y))$adj.r.squared
test.run <- moos.DO.pred %>% group_by(SM.date) %>% summarise(adj.R2 = fit_model(DO.obs,DO.mod))
moos.DO.pred <- full_join(moos.DO.pred, test.run)
rsq <-  summary(lm(moos.DO.pred$DO.mod~moos.DO.pred$DO.obs))$r.squared

p1 <- ggplot(moos.DO.pred, aes(x = solar.time)) + geom_point(aes(y=DO.obs, colour = "Observed DO"), color = "darkcyan") + geom_line(aes(y = DO.mod, colour= "Modeled DO"), color = "blue4") + theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank() ) + labs(colour="Green", y = "DO (mg/L)") +  theme(legend.position="none") + ggtitle("Observed (points) and Modeled (lines)")
p2 <- ggplot(moos.DO.pred, aes(x = solar.time)) + geom_point(aes(y=adj.R2))
q.fig <- ggplot(data = data.moos.mm.all, aes(x = solar.time)) +geom_point(aes(y=discharge))

grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2)))
```             

```{r fig.width = 10, fig.height=8}
grid.newpage()
grid.draw(rbind(ggplotGrob(p1), ggplotGrob(p2), ggplotGrob(rhat),ggplotGrob(q.fig), ggplotGrob(k600),ggplotGrob(gpp), ggplotGrob(er)))

```